### ISSUE TITLE
Expand flexibility of manual citations

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#100]
Currently, users can supply manual bibliographic metadata in `manual-references.json`, which must consist of CSL JSON where each item has an extra `standard_citation` field.

This can be restrictive in a couple ways. Oftentimes, users may have existing bibliographic metadata in an alternative format, such as `.bib` files. Additionally, since `standard_citation` is not a standard CSL JSON field, users must always modify the manual metadata from however it was generated. Finally, when wanting to do a `raw` citation, they must place `raw:` before their citation id.

I propose the following changes to enable more input formats than just CSL JSON and relax how `standard_citation` must be specified:

1. use `pandoc-citeproc --bib2json` to convert bibliographies from a variety of formats to CSL JSON
2. allow specifying multiple manual reference metadata files, possibly of varying types. For example, a user could pass a `.bib` file as well as a CSL file.
3. if `standard_citation` is not specified, fallback to using `id` to set `standard_citation`. `id` is built into CSL JSON and `.bib` files will not be able to set `standard_citation` (only `id`).
4. when inferring `standard_citation` from `id`, if no citation source prefix is supplied (e.g. `doi:`, `pmid:`), assume `raw:` citation.

These features would help address feedback @tpoisot provided us, where his group would like to use existing bibliographic metadata files without any special edits in a Manubot based workflow. @agitter and others, what do you think?

Some of this work is implemented in https://github.com/manubot/manubot/pull/99, which proposes a pandoc-filter for cite-by-id. However, I may split it out into a distinct pull request.

**Comment by agitter** [comment]
Working with `manual-references.json` can be cumbersome.  If we have support for manual `.bib` files, it would likely lead to some users to skip cite-by-id entirely in favor of existing manually-curated references.  That's not my preferred way to use Manubot, but supporting multiple writing workflows seems to be a good step toward expanding the user base.

I'd like to think more about the configuration and user experience.  Would users modify the build script to refer to one or more CSL JSON or `.bib` files?  Would this break backward compatibility with anything?

This will give us two different ways to cite manual references using `id` or `standard_citation`, which could make the documentation more confusing.

**Comment by dhimmel** [comment]
> lead to some users to skip cite-by-id entirely in favor of existing manually-curated references. That's not my preferred way to use Manubot

Agreed, since one goal of the project is to increase adoption of cite-by-ID. However, I think if we can attract users that would like to start with their legacy bibliographic metadata collections, we can transition them over time to using cite-by-ID. For example, allowing a `.bib` file would make it much easier to port an existing latex manuscript. Then I think it's likely authors will use cite-by-id for new citations.

> Would users modify the build script to refer to one or more CSL JSON or .bib files?

Currently, `manubot process` doesn't have an option to specify the location of `manual-references.json`. Instead it assumes it's located in `--content-directory`. We could create an option, or we could have it just find all `manual-references*` files in `--content-directory`.

I'm also thinking we should have a separate subcommand, named something like `manubot bib2json` or `manubot references`, to combine reference files. So we could also just have users run this command as a separate build command to create `manual-references.json`.

> Would this break backward compatibility with anything?

I don't think breaking backwards compatibility would be necessary.

> This will give us two different ways to cite manual references using id or standard_citation, which could make the documentation more confusing.

Yes will have to think about what we want to do here. Somewhat related/unrelated, since standard_citation gets dropped, we should probably embed this information in the note field.

**Comment by dhimmel** [comment]
I am beginning to think that we should use the CSL `id` field rather than the nonstandard `standard_citation` field to store standard_citations. Since `standard_citation` is not part of the CSL JSON schema, it could be problematic for compatibility. In addition we will use the `note` field to store any important values.

`csl_item_set_standard_citation` could adopt the following behavior:

#### DOI example

input:
```yaml
id: doi:10.7554/eLife.03401
type: article-journal
```

output:
```yaml
id: doi:10.7554/elife.03401
type: article-journal
note: "original_id: doi:10.7554/eLife.03401
       standard_citation: doi:10.7554/elife.03401"
```

#### raw example

input:
```yaml
id: my-citation-tag
type: article-journal
```

output:
```yaml
id: raw:my-citation-tag
type: article-journal
note: "original_id: doi:my-citation-tag
       standard_citation: raw:my-citation-tag"
```

With citation-by-identifier, users cite ids, such that `id` should be the standard_citation. @agitter does that make sense to you? If so, I will revise #104 with this change. Standard citations specified using `standard_citation` in manual-references will still work, but going forward, we would recommend putting the standard_citation in the `id` field.

**Comment by agitter** [comment]
@dhimmel I like that plan.  Using standard fields is a good idea.

I didn't understand the `note: "original_id: doi:my-citation-tag` line in the raw example output.  Is `doi:` a typo, or where did it come from?

**Comment by dhimmel** [comment]
I didn't understand the note: `"original_id: doi:my-citation-tag` line

> was a typo
