### ISSUE TITLE
manubot process / build.sh requires CI folder?

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot#102]
Either the regular build or the webpage.py build seems to fail if the CI folder is not present in the directory? This should either not cause it to fail, or at least provide a more deliberate/understandable error.

User's who are just building locally and are not interested in publishing to gh-pages might appreciate this. I ran into this when testing the plugins in my local test directory (stripped of all the non-essential stuff).

**Comment by dhimmel** [comment]
What is the error message currently?

**Comment by vincerubinetti** [comment]
```
(manubot) vincerubinetti@greenelab-vince-rubinetti:~/Desktop/projects/manubot-rootstock$ sh build/build.sh; python build/webpage.py
Retrieving and processing reference metadata
Traceback (most recent call last):
  File "/home/vincerubinetti/miniconda2/envs/manubot/bin/manubot", line 11, in <module>
    sys.exit(main())
  File "/home/vincerubinetti/miniconda2/envs/manubot/lib/python3.6/site-packages/manubot/command.py", line 141, in main
    function(args)
  File "/home/vincerubinetti/miniconda2/envs/manubot/lib/python3.6/site-packages/manubot/process/process_command.py", line 25, in cli_process
    args.cache_directory.mkdir(exist_ok=True)
  File "/home/vincerubinetti/miniconda2/envs/manubot/lib/python3.6/pathlib.py", line 1246, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/vincerubinetti/miniconda2/envs/manubot/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'ci/cache'
webpage/v/local exists: replacing it with an empty directory
Namespace(checkout=None, freeze_directory=PosixPath('webpage/v/freeze'), latest_directory=PosixPath('webpage/v/latest'), no_ots_cache=False, ots_cache=PosixPath('ci/cache/ots'), output_directory=PosixPath('output'), version='local', version_directory=PosixPath('webpage/v/local'), versions_directory=PosixPath('webpage/v'), webpage_directory=PosixPath('webpage'))
['local']
```

**Comment by dhimmel** [comment]
rootstock's `build.sh` calls `manubot process` with the following command ([source](https://github.com/manubot/rootstock/blob/723319f07d44198ee9baad2fff518fe533c03c3a/build/build.sh#L10-L14)):

```sh
manubot process \
  --content-directory=content \
  --output-directory=output \
  --cache-directory=ci/cache \
  --log-level=INFO
```

So the issue is that `build.sh` is specifying a cache directory that doesn't exist. We could look into recursively creating the directories or a better error message. Here's the `--cache-directory` doc:

```
  --cache-directory CACHE_DIRECTORY
                        Custom cache directory. If not specified, caches to
                        output-directory.
```

So you could always remove that line from the `build` script.

>  I ran into this when testing the plugins in my local test directory (stripped of all the non-essential stuff).

Currently, we don't recommend deleting any files in rootstock besides `delete-me.md` and `SETUP.md`. In the future, we can think more about what should be considered essential versus non-essential.

**Comment by dhimmel** [comment]
Another option would be to disable the cache if an invalid path is specified, and log a warning. I don't think we currently have a way to disable to the cache entirely (rather than just reset), but we could add it.

**Comment by agitter** [comment]
Removing that line from the build script seems like a good workaround.  Manubot could also log a warning and use the default output-directory for the cache if the provided cache-directory path is invalid.

**Comment by vincerubinetti** [comment]
In general, it should give pretty clear and simple errors, like "/ci directory can't be found. This directory is required to build. See manubot.org for more information." Or something similar. And that should apply to all the essential files/folders, eg "Can't find style.csl, the citation styles file..."

**Comment by dhimmel** [comment]
What about creating `--cache-directory` with `parents=True` if it doesn't exist? We already make the directory if its parent exists:

https://github.com/manubot/manubot/blob/351f4bac474d478b59283aa57afb8f7b625c0e80/manubot/process/process_command.py#L23-L26

The question is then whether we should do the same with the `--output-directory`:

https://github.com/manubot/manubot/blob/351f4bac474d478b59283aa57afb8f7b625c0e80/manubot/process/process_command.py#L16-L17
