### ISSUE TITLE
Sorting documents numbered >99 unexpectedly positioned in front of 99.back-matter

### ISSUE THREAD

**Issue by slochower** [manubot/manubot#106]
https://github.com/manubot/manubot/blob/a2eb7d83fe40c9cf5deae8ce06504201e738e766/manubot/process/manuscript.py#L32

I naively created `100.si.md` that I thought would be sorted after `99.back-matter` (where the references are) but it gets sorted in front.

```
Manuscript content parts:
00.front-matter
01.abstract
02.main-text
03.results
100.si
99.back-matter
```

**Comment by agitter** [comment]
Do you think this behavior is a problem, or rather does it need to be better documented?  I think it is reasonable for the filenames to be sorted in this manner, which matches how GitHub sorts them.  We do need to make sure that users know how to place text in the desired location though.

One convention would be to switch to a three digit `000`, `001`, etc. file naming scheme to add the supplement in the desired location.

**Comment by slochower** [comment]
> Do you think this behavior is a problem, or rather does it need to be better documented?

Probably just this. I could add a one sentence PR to `USAGE` that examples this, probably. Just noting it here.

Although I'm currently debating having the SI in the same manuscript versus not. Having it there makes references and other things better, on the other hand, lot of journals want things like different figure numbering for SI (restart the counter and use S1, S2, ...) which is tough with a our current framework of smooshing all the separate Markdown documents together before rendering.

**Comment by dhimmel** [comment]
> One convention would be to switch to a three digit 000, 001, etc. file naming scheme to add the supplement in the desired location.

Better would be to move back-matter to `90.`

**Comment by slochower** [comment]
This is true, no reason to go to triple digits unless necessary :)
