### ISSUE TITLE
Parsing of URL reference appears to mangle specific URL

### ISSUE THREAD

**Issue by slochower** [manubot/manubot#107]
I tried to cite `[@url:https://openforcefield.org]`.

The bibliography is rendered as:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/5393995/56437316-b5200580-6293-11e9-8c6f-034a36721782.png">

In `references.json`, I see:

```
  {
    "type": "webpage",
    "title": "Open Force Field Initiative",
    "abstract": "An open source, open science, and open data approach to better force fields",
    "URL": "//openforcefield.org/",
    "language": "en-us",
    "author": [
      {
        "family": "newpixcom",
        "given": ""
      }
    ],
    "accessed": {
      "date-parts": [
        [
          "2019",
          4,
          19
        ]
      ]
    },
    "id": "OhpH7vfg"
```

It seems that the URL field is being incorrectly parsed.

(There may be misconfiguration on their end, I'm not sure, but I think that `manubot`s processing of the URL is also incorrect.)

**Comment by slochower** [comment]
FYI: This appears to be a bug in the Zotero parser because I can replicate the problem if I attempt to add the URL to Zotero directly.

**Comment by agitter** [comment]
The website itself may be the root cause.  The page source has:
`<meta property="og:url" content="//openforcefield.org/" />`.

**Comment by slochower** [comment]
That's interesting, since the page itself is hosted by GitHub Pages: https://github.com/openforcefield/openforcefield.org. Probably a bug in the theme. Still, I was surprised that the URL field in `references.json` is written by something returned by the translator and the not necessarily the URL field entered in the citation `[@url:this]`.

**Comment by slochower** [comment]
Filed a bug upstream (https://github.com/openforcefield/openforcefield.org/issues/94), thanks @agitter:

**Comment by dhimmel** [comment]
> FYI: This appears to be a bug in the Zotero parser because I can replicate the problem if I attempt to add the URL to Zotero directly.

Yes. I think https://github.com/zotero/translators is probably the right place to report this if you think it's a Zotero bug. However, I think it should most likely be considered a webpage bug. Perhaps better error checking and fallbacks would be possible by Zotero's web translator, IDK.

**Comment by slochower** [comment]
Yup. Agree there's a configuration problem on webpage. My initial bug report was based on the expectation that `manubot`s references JSON would at least have what I typed in the `"url"` field and not something processed. I *guess* someone could have a website report a different (malicious?) URL in the `meta` tag so the citation would point somewhere bad. I would not consider this very likely or necessary for us to mitigate.
