### ISSUE TITLE
CSL JSON type for "computerProgram" not allowed

### ISSUE THREAD

**Issue by slochower** [manubot/manubot#112]
Does Manubot not accept the CSL type "computerProgram"? I get this type as an output directly from Zotero. The citation is correct; it is for a computer program. Looking at the [schema](https://github.com/citation-style-language/schema/blob/master/csl-types.rnc), I see nothing related to computer program. @dhimmel what do you suggest for a type here? I've included the stanza from `manual-references.json` at the end of this post.

The error returned by `manubot` is slightly cryptic:

```
## WARNING
'type' is a required property
requried element missing at: 0/type
## WARNING
'type' is a required property
requried element missing at: 0/type
## WARNING
'type' is a required property
requried element missing at: 0/type
## WARNING
'type' is a required property
requried element missing at: 0/type
## WARNING
'type' is a required property
```

Maybe it could say that it does recognize the known type.

Entry in `manual-references.json`:
```
  {
    "type": "computerProgram",
    "standard_citation": "raw:amber2018",
    "title": "AMBER 2018",
    "creators": [
      {
        "firstName": "D.A.",
        "lastName": "Case",
        "creatorType": "programmer"
      },
[...many more creators...]
```
This was lifted directly from a JSON export via the Zotero desktop client.

**Comment by dhimmel** [comment]
It looks like you exported from Zotero into Zotero JSON format. Is it possible to export from Zotero into CSL JSON format? For example, `creators` is also not valid CSL JSON.

> Looking at the schema, I see nothing related to computer program.

With CSL JSON you are limited to the types in the schema. It is a big omission to not have software. Perhaps you could use "dataset", "website", or "report". Manubot's CSL style doesn't actually do any type-dependent formatting, so it won't really matter.

> The error returned by manubot is slightly cryptic:

Yeah, we implemented a general solution with the tradeoff of having poor warning messages. We could consider making a special case to the CSL validation to deal with types, because that is where these warnings come from.

**Comment by slochower** [comment]
> It looks like you exported from Zotero into Zotero JSON format. Is it possible to export from Zotero into CSL JSON format?

Interesting, I see! I'm not 100% what the different export formats map to, in Zotero. I just tried "Better CSL JSON" as export. Unfortunately, this mapped the citation `type` to a `book`.

> Perhaps you could use "dataset", "website", or "report". Manubot's CSL style doesn't actually do any type-dependent formatting, so it won't really matter.

Ah, right. Okay.

> Yeah, we implemented a general solution with the tradeoff of having poor warning messages. We could consider making a special case to the CSL validation to deal with types, because that is where these warnings come from.

Could be low priority :)

**Comment by slochower** [comment]
Changing `creator` to `author` and getting rid of `creatorType` does allow the citation to go through. Oh and changing type to `book`. The order of the authors is preserved (which in my case is almost alphabetical, but not quite); this is probably the correct behavior, just noting it here.

**Comment by dhimmel** [comment]
> I just tried "Better CSL JSON" as export. Unfortunately, this mapped the citation type to a book.

Given that no CSL type is very accurate, this is not terrible. It seems like the Zotero "Better CSL JSON" will most likely produce valid CSL, so best to stick with that.

**Comment by slochower** [comment]
Yep. I'll close this issue, though it may still serve as a reference if this pops up for other users.
