### ISSUE TITLE
Choose service for docs generation

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot#117]
We should choose a service/product to help us write and generate the docs for all of Manubot. It can be a full service that manages the writing of the docs and also hosts it (like `readthedocs`) or it can just be some kind of tool that generates a static docs website from some simple markdown. 

Here are the most popular ones, it seems:

[readthedocs](https://readthedocs.org/)
[sphinx](http://www.sphinx-doc.org/en/master/)
[gitbook](https://www.gitbook.com/pricing)

We could even just do it "manually" with Jekyll, and it might not be much more difficult than a docs-specific generation tool.

**Comment by dhimmel** [comment]
One consideration will be whether we want the docs for the `manubot` python package also in this location. I think so? If so, we will want a way to automatically generate rendered documentation from the python source code. I believe at least some of the services above support this.

Currently, it seems like we have at least three sources of documentation:

1. Usage documentation from rootstock's USAGE.md
2. Setup documentation from rootstock SETUP.md
3. Documentation for the `manubot` python package

Another consideration is versioning. Currently, we version based on the git commit hashes, but this may no longer be possible or desirable?

**Comment by epogrebnyak** [comment]
Correction: readthedocs  is a rendering service using sphinx. Gitbook is ok for generating for markdown-based sites, bit not documentation from code. We are pretty much constrained to sphinx on python.

**Comment by dhimmel** [comment]
One option I'd like to look into is https://github.com/timothycrosley/portray.

**Comment by dhimmel** [comment]
Docs are now available, auto-generated using portray, at https://manubot.github.io/manubot/. Not perfect, but enough to let us browse the docs and see where we need to improve.
