### ISSUE TITLE
How to start???

### ISSUE THREAD

**Issue by sbonaretti** [manubot/manubot#122]
I found it!

**Comment by agitter** [comment]
I'm glad you were able to find what you were looking for @sbonaretti.

Our general recommendation for anyone else who has this question:
- If you want to experience Manubot by editing an existing manuscript, see <https://github.com/manubot/try-manubot>.   From there, you can try editing the content through the GitHub web interface.  Or create a branch locally with a Git client and then make a pull request through GitHub.
- If you want to create a new Manuscript, see <https://github.com/manubot/rootstock>.  SETUP.md provides the instructions for copying the template and creating your own manuscript and USAGE.md describes the supported syntax.  There are instructions to build the manuscript locally, but it is possible to only use Travis CI to build the HTML and PDF outputs after pushing content changes to GitHub.

**Comment by sbonaretti** [comment]
Thanks! Sorry for not following up properly. I had an issue with directories.
I could not find the file `environment.yml`. Once I found it, I understood that I have to run `conda env create --file environment.yml` in the directory `build`, while `sh build.sh` in the parent directory.
