### ISSUE TITLE
Make source prefixes of citation keys optional

### ISSUE THREAD

**Issue by nichtich** [manubot/manubot#123]
Source prefixes (`url:`, `doi:`, `pmcid:`, `wikidata:`...) are needles: [citation-js](https://citation.js.org/) can automatically detect URL, DOI, PMID, Wikidata identifier... to route requests for bibliographic data to different sources. Just use regular expressions to guess the source.

**Comment by agitter** [comment]
I'm interested to learn more about this and what sources citation-js supports.  I'm still reading through its documentation and https://peerj.com/preprints/27466/.  The [input formats tutorial](https://citation.js.org/api/tutorial-input_formats.html) indicates DOIs, doi.org URLs, and Wikidata entity ids are the supported standard identifiers.  Does citation-js support general URLs, PMIDs, etc?

The [demo](https://citation.js.org/) seems consistent with that:
`const data = await Cite.async('10.7287/peerj.preprints.27466v1')`
works perfectly without the DOI prefix.

Using a URL like
`const data = await Cite.async('https://peerj.com/preprints/27466/')`
returns `Error: This format is not supported or recognized`.  Same for the arXiv ids, PMIDs, and PMCIDs I tried.

doi.org URLs like `https://doi.org/10.7287/peerj.preprints.27466v1` do work.

**Comment by dhimmel** [comment]
I see three main benefits of including source prefixes in citations:

1. unambiguous citations for humans: `@pmid:31233491` lets human users know that the citation is pointing a PubMed record. I imagine few users would be able to immediately know `@31233491` was a PubMed ID.

2. unambiguous citations for machines: I am not sure that no identifiers are shared between sources. Currently, we support the following sources (and hopefully more in the future):
    https://github.com/manubot/manubot/blob/025b7c78e96d37cb81388bf739411dfe82969780/manubot/cite/util.py#L7-L15

3. Sources can be used to perform more stringent error checking of identifiers. Tags / citations keys become more confusing / difficult to handle when it's not clear whether something is a key or a resolved identifier. For example, `@31233491` could be a tag or a PubMed ID. Maybe the user intended it to be a tag, but had a typo, and thus it's now treated as an erroneous PubMed ID.

The main benefits I see to allowing users to omit the source prefix are:

1. convenience
2. unified behavior with other tools that do not require the prefix, like [citation-js](https://citation.js.org/) or zotero's [translation-server](https://github.com/zotero/translation-server)

However, I think convenience is minimal when users are aware of what source an identifier belongs to. Convenience increases for users who don't know what source / identifier they're actually citing. I do see a danger where users start citing works with less and less understanding of the associated persistent identifier and the whole standardization and machine-readability benefits of citation-by-identifier start to be diminished.

We will consider whether and how we want to enable source-prefix inference as part of https://github.com/manubot/manubot/issues/114. Personally, I am hesitant, but could imagine some designs that mitigated many of the risks, such as making sourceless identifier support an opt-in feature.

**Comment by dhimmel** [comment]
Open PR https://github.com/manubot/manubot/pull/277 adds support for inferring citekey prefixes, which would be enabled by default.

For example: `manubot cite --md 1 PMC4304851 10/b6vnmd` would output:

> 1. **Formate assay in body fluids: application in methanol poisoning.**
> AB Makar, KE McMartin, M Palese, TR Tephly
> *Biochemical medicine* (1975-06) <https://www.ncbi.nlm.nih.gov/pubmed/1>
> DOI: [10.1016/0006-2944(75)90147-7](https://doi.org/10.1016/0006-2944(75)90147-7) · PMID: [1](https://www.ncbi.nlm.nih.gov/pubmed/1)
> 
> 2. **Lung cancer incidence decreases with elevation: evidence for oxygen as an inhaled carcinogen**
> Kamen P Simeonov, Daniel S Himmelstein
> *PeerJ* (2015-01-13) <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4304851/>
> DOI: [10.7717/peerj.705](https://doi.org/10.7717/peerj.705) · PMID: [25648772](https://www.ncbi.nlm.nih.gov/pubmed/25648772) · PMCID: [PMC4304851](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4304851)
> 
> 3. **An evaluation of machine-learning methods for predicting pneumonia mortality**
> Gregory F Cooper, Constantin F Aliferis, Richard Ambrosino, John Aronis, Bruce G Buchanan, Richard Caruana, Michael J Fine, Clark Glymour, Geoffrey Gordon, Barbara H Hanusa, … Peter Spirtes
> *Artificial Intelligence in Medicine* (1997-02) <https://doi.org/b6vnmd>
> DOI: [10.1016/s0933-3657(96)00367-3](https://doi.org/10.1016/s0933-3657(96)00367-3)

Feedback welcome.
