### ISSUE TITLE
Generalize variables stored during CI builds

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#130]
Currently, Manubot stores the repository and commit metadata when it is run on Travis CI:
https://github.com/manubot/manubot/blob/66c1c8733038c626ddff203b984d2e4ced943281/manubot/process/util.py#L189-L199

Per https://github.com/manubot/rootstock/issues/198#issuecomment-517814975 we would like to generalize this to store similar metadata for other continuous integration services.  AppVeyor is of immediate interest because it will be used for pull request build previews in https://github.com/manubot/rootstock/pull/262.

AppVeyor's environment variables are listed at https://www.appveyor.com/docs/environment-variables/.  We likely want:
- `APPVEYOR`
- `APPVEYOR_PROJECT_SLUG`
- `APPVEYOR_REPO_COMMIT`

We could also store which CI service was used in a new variable.  When updating `manubot/rootstock`, we'll also need to update the front matter permalink, which is only relevant for Travis CI.

**Comment by dhimmel** [comment]
I will work on the implementation of this

> we'll also need to update the front matter permalink, which is only relevant for Travis CI.

Currently, [`00.front-matter.md`](https://github.com/manubot/rootstock/blob/3defccfbea9d088f3b6885e1bf18158c6a05f467/content/00.front-matter.md) contains:

```markdown
{% if ci_source is defined -%}
([permalink](https://{{ci_source.repo_owner}}.github.io/{{ci_source.repo_name}}/v/{{ci_source.commit}}/))
{% endif -%}
```

So do we want to omit the permalink altogether for AppVeyor builds or do we want to give the artifact link?

**Comment by agitter** [comment]
I hadn't thought about giving the artifact link.  I like that idea.  The artifacts aren't permanent though, so it would be a slight abuse of terminology to call it a permalink (even though AppVeyor does in their [webhook doc](https://www.appveyor.com/docs/notifications/#webhook-payload-default)).

I'm also okay discarding the link completely if that's easier.  Or adding a new `ci_source.deploy` flag to indicate whether we want to display the link.
