### ISSUE TITLE
test_ci.py makes travis checks on a fork to fail

### ISSUE THREAD

**Issue by epogrebnyak** [manubot/manubot#140]
I use manubot repo fork to test code changes, and Travis builds between branches of a fork indicate test success or failure. `test_ci.py` is hardcoded to work on manubot/manubot repo only:

https://github.com/manubot/manubot/blob/307b339a4e600406345d388e20e74cc833cc43c5/manubot/process/tests/test_ci.py#L12-L30

Any ideas on how this can be changed?

**Comment by dhimmel** [comment]
What if we add a second skipif that will skip the test unless the travis environment variable `TRAVIS_REPO_SLUG` equals `manubot/manubot`?

This would weaken the test slightly, for example causing it to be skipped if Travis CI no longer set `TRAVIS_REPO_SLUG`.

Perhaps another option would be to use pytest [custom markers](http://doc.pytest.org/en/latest/example/markers.html). For example, you could decorate tests with `@pytest.mark.forksfail` and then execute pytest with the `-m "not forksfail"` option. But then you'd have to modify `.travis-ci.yml` for your fork... unless we conditionally specified the option in the travis pytest command.

**Comment by epogrebnyak** [comment]
I think we can weaken the tests, eg `assert isinstance(info['repo_slug'], str) and info['repo_slug']`. 

But before that - there must have been a reason you wanted to have checked for `info['repo_slug'] == 'manubot/manubot'`. Is this important for the pdf build process?

**Comment by dhimmel** [comment]
> there must have been a reason you wanted to have checked for `info['repo_slug'] == 'manubot/manubot'`

We wanted to make sure that `get_continuous_integration_parameters` properly detects the repository account/name on GitHub. The test is already weakened by having the account and name both as `manubot` here, so it's looking for `manubot/manubot` rather than two different values such as `manubot/rootstock`. These values are used to template portions of manuscripts that need to link to the GitHub source code.

> I think we can weaken the tests, eg `assert isinstance(info['repo_slug'], str) and info['repo_slug']`, at least on fallback `TRAVIS_REPO_SLUG` =! `manubot/manubot`.

Sounds good to me. While I would like a stronger test, I understand how detecting these environment variables is a difficult thing to hardcode in tests because they change, and therefore weakening is one solution.

**Comment by epogrebnyak** [comment]
More granuarly, we can assume repo name has to be manubot (which is reasonable for a fork):

 `assert info['repo_name'] == 'manubot'`

And can move checking the owner `info['repo_owner'] == 'manubot'` into separate test which is conditional on `TRAVIS_REPO_SLUG` equalling  `manubot/manubot`.

Also will be affected:
```
     assert info['build_url'].startswith('https://travis-ci.com/manubot/manubot/builds/') 
     assert info['job_url'].startswith('https://travis-ci.com/manubot/manubot/jobs/') 
```

Also maybe some grouping of tests into classes (eg testing generic properties on `info`, TRAVIS/APPVEYOR-specific properties and separating test functions or class that is dependent on a fork.)

**Comment by dhimmel** [comment]
> And can move checking the owner info['repo_owner'] == 'manubot' into separate test which is conditional on TRAVIS_REPO_SLUG equalling manubot/manubot.

Good idea. We could also expose the forksfail assertions in an if statement inside the current test. Whatever you think is best and most straightforward.
