### ISSUE TITLE
test_cite_command_render_stdout[--format=jats] fails with pandoc 2.7.3

### ISSUE THREAD

**Issue by epogrebnyak** [manubot/manubot#144]
To be further investigated, maybe utf-8 local file reading issue similar to #143

**Comment by dhimmel** [comment]
Here's the source code
https://github.com/manubot/manubot/blob/df480ae2f9de33569a040de420d6a57924927dfe/manubot/cite/tests/test_cite_command.py#L68-L99

Looks like we need to specify the encoding in `.read_text`. There failures are showing the value of testing on a Windows system whose default encoding is not UTF-8.

**Comment by epogrebnyak** [comment]
Another little mistery - I'm running a command line with `--format jats` and saving the output to jats.txt:

```
manubot cite --render --csl https://github.com/greenelab/manubot-rootstock/raw/e83e51dcd89256403bb787c3d9a46e4ee8d04a9e/build/assets/style.csl arxiv:1806.05726v1 doi:10.7717/peerj.338 pmid:29618526 --format jats > jats.txt
```

then doing file compare with reference file - `references-jats.xml` and the output is slightly different in schema of the files. Ok, but why does this happen on a local Windows machine and is not an error on a remote linux machine?  Any clues?

My local panodc is 2.7.3.

Here is a lengthy file compare, don't know how to highlight it better:

```
λ fc references-jats.xml jats.txt
Сравнение файлов references-jats.xml и JATS.TXT
***** references-jats.xml
<article-meta>
</article-meta>
***** JATS.TXT
<article-meta>
<pub-date pub-type="epub">
<year></year>
</pub-date>
</article-meta>
*****

***** references-jats.xml
  location</article-title><source>PeerJ</source><publisher-name>PeerJ</publisher-name><date><day>03</day><month>04</month><year
>2014</year></date><volume>2</volume><pub-id pub-id-type="doi">10.7717/peerj.338</pub-id><ext-link ext-link-type="pmid" xlink:h
ref="http://www.ncbi.nlm.nih.gov/pubmed/<ext-link ext-link-type="uri" xlink:href="https://www.ncbi.nlm.nih.gov/pubmed/24765572"
>24765572</ext-link>" xlink:type="simple"><ext-link ext-link-type="uri" xlink:href="https://www.ncbi.nlm.nih.gov/pubmed/2476557
2">24765572</ext-link></ext-link><ext-link ext-link-type="uri" xlink:href="https://doi.org/gfrfbm">https://doi.org/gfrfbm</ext-
link></element-citation></ref>
  <ref id="ref-3"><element-citation publication-type="journal"><person-group person-group-type="author"><name><surname>Ching</s
***** JATS.TXT
  location</article-title><source>PeerJ</source><publisher-name>PeerJ</publisher-name><date><day>03</day><month>04</month><year
>2014</year></date><volume>2</volume><pub-id pub-id-type="doi">10.7717/peerj.338</pub-id><pub-id pub-id-type="pmid">24765572</p
ub-id><ext-link ext-link-type="uri" xlink:href="https://doi.org/gfrfbm">https://doi.org/gfrfbm</ext-link></element-citation></r
ef>
  <ref id="ref-3"><element-citation publication-type="journal"><person-group person-group-type="author"><name><surname>Ching</s
*****

***** references-jats.xml
  Interface</source><date><month>04</month><year>2018</year></date><volume>15</volume><issue>141</issue><pub-id pub-id-type="do
i">10.1098/rsif.2017.0387</pub-id><ext-link ext-link-type="pmid" xlink:href="http://www.ncbi.nlm.nih.gov/pubmed/<ext-link ext-l
ink-type="uri" xlink:href="https://www.ncbi.nlm.nih.gov/pubmed/29618526">29618526</ext-link>" xlink:type="simple"><ext-link ext
-link-type="uri" xlink:href="https://www.ncbi.nlm.nih.gov/pubmed/29618526">29618526</ext-link></ext-link><ext-link ext-link-typ
e="uri" xlink:href="https://www.ncbi.nlm.nih.gov/pubmed/29618526">https://www.ncbi.nlm.nih.gov/pubmed/29618526</ext-link></elem
ent-citation></ref>
</ref-list>
</back>
***** JATS.TXT
  Interface</source><date><month>04</month><year>2018</year></date><volume>15</volume><issue>141</issue><pub-id pub-id-type="do
i">10.1098/rsif.2017.0387</pub-id><pub-id pub-id-type="pmid">29618526</pub-id><ext-link ext-link-type="uri" xlink:href="https:/
/www.ncbi.nlm.nih.gov/pubmed/29618526">https://www.ncbi.nlm.nih.gov/pubmed/29618526</ext-link></element-citation></ref>
</ref-list>
<fn-group>
</fn-group>
</back>
```

**Comment by epogrebnyak** [comment]
> Looks like we need to specify the encoding in .read_text. There failures are showing the value of testing on a Windows system whose default encoding is not UTF-8.

Not really an encoding issue this time, unfortunately - my local output from jats/xml has a slightly different schema, see above. 

Maybe save another variety of output and check output against two reference files? A bit dirty - but I have no idea how to trace/stabilise different behaviours of pandoc.

**Comment by dhimmel** [comment]
> My local panodc is 2.7.3.

The expected output was generated from Pandoc 2.7.3, which is what our tests use:

https://github.com/manubot/manubot/blob/cf9564dd4a31701e48a487ecd716b2cea6aca53a/.appveyor.yml#L24

My guess is that this is causing the discrepancy. One annoying thing about these tests is how version specific they are... not sure best way to relax test.

Note that we can update repo to use 2.7.3 output, but that doesn't fix the root cause of the problem.

**Comment by epogrebnyak** [comment]
Maybe list several reference `.xml` files? It is a bit of a reverse engineering hack, but passes the test. 
Also can rename 'references-jats-bis.xml' to 'references-jats-2.7.3.xml'.

```
def test_cite_command_render_stdout_for_jats():
    pandoc_version = get_pandoc_version()
    if pandoc_version < (2, 5):
       pytest.skip(f"Test for 'jats' output assumes pandoc >= 2.5")
    flag = False   
    for filename in ['references-jats.xml', 'references-jats-bis.xml']:
        expected = (
            pathlib.Path(__file__).parent
            .joinpath('cite-command-rendered', filename)
            .read_text()
        )
        args = [
            'manubot', 'cite', '--render',
            '--csl', 'https://github.com/greenelab/manubot-rootstock/raw/e83e51dcd89256403bb787c3d9a46e4ee8d04a9e/build/assets/style.csl',
            'arxiv:1806.05726v1', 'doi:10.7717/peerj.338', 'pmid:29618526',
            '--format', 'jats'
        ]
        process = subprocess.run(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
        )
        print(shlex_join(process.args))
        print(process.stdout)
        print(process.stderr)
        if process.stdout == expected:
            flag = True
    assert flag
```
A more systematic approach could have been detecting a pandoc version used and supplying a name of the reference xml file based on the version, it is probably cleaner. Also would not require a new test, can do that in parametrisation for existing test `def test_cite_command_render_stdout()`.

**Comment by dhimmel** [comment]
> A more systematic approach could have been detecting a pandoc version used and supplying a name of the reference xml file based on the version, it is probably cleaner

That seems like a good approach to me. If the corresponding versioned file does not exist, we could skip the test... unless the `CI` environment variable is set and then we fail. I want to make sure that the tests are not skipped on CI due to versioning and we accidentally stop testing this. But also want to make sure local builds don't fail if they don't need to.

We also could just keep a single set of expected files, but skip if pandoc version was not the version that generated the files.

**Comment by epogrebnyak** [comment]
> We also could just keep a single set of expected files, but skip if pandoc version was not the version that generated the files.

This would simplify the tests a lot (we do a lot of checks on pandoc version), but weakens local testing - so pushing to Travis can produce surprises that are hard to track unless you know the stroy why things were skipped.

> I want to make sure that the tests are not skipped on CI due to versioning

Maybe this - if there is an exact version match with reference file - test against it, fail if not passed. If there is not exact version match - test against a default files version which is current set of files produced by 2.7.2., fail if not passed.

This way we abstract from CI or not CI and keep local and remote tests more or less in sync.

**Comment by epogrebnyak** [comment]
Please see https://github.com/manubot/manubot/pull/146
