### ISSUE TITLE
multiple entry points to manubot.cite

### ISSUE THREAD

**Issue by epogrebnyak** [manubot/manubot#145]
Got a questoin about usage of various parts of manubot.cite in larger manubot. 

There are two cases:

- submodule API: using `manubot.cite.__init__.py` functions
- using individual funcitons from `manubot.cite`, formerly from `manubot.cite.util`, example: 

https://github.com/manubot/manubot/blob/307b339a4e600406345d388e20e74cc833cc43c5/manubot/process/bibliography.py#L6-L13

There is a possibility `manubot.cite.__init__.py` will contain classes like `CSL_Item` and `CiteKey` and there will be no imports from submodule internals.

Also I see that some functions from ex-`manubot.cite.util` are not used inside `manubot.cite`, but designed specifically for `bibliography.py`. 

Need opinion about encapsulation: should everythting that is used from `manubot.cite` submodule be imported from  `__init__.py`? 

Also raised [here](https://github.com/manubot/manubot/pull/139#issuecomment-533839119)

**Comment by dhimmel** [comment]
The design philosophy up until this point is to have as little as possible imported into `manubot.cite.__init__.py`, which currently exposes:
 https://github.com/manubot/manubot/blob/307b339a4e600406345d388e20e74cc833cc43c5/manubot/cite/__init__.py#L1-L6

Currently the imports in this file are there mostly for purposes of backwards compatibility. Originally, we implemented lot's of things in `__init__.py`. We then moved all the functionality to submodules, but kept imports that external projects were using in their codebases. This happened to be the functions currently exposed by `__init__.py`.

The reason we haven't exposed more functions under `manubot.cite` is that the API and structure was rapidly evolving and we didn't want the burden of maintaining imports in multiple locations.

In general, I think it makes sense to keep `__init__.py` minimal, but I am okay with exposing more functions directly under `manubot.cite`, should we feel that aspect of the API is somewhat stable.

Another consideration is that we want to keep imports lazy, such that using one aspect of `manubot.cite` doesn't invoke the entire set of dependencies for tasks where they're not needed.

> Also I see that some functions from ex-manubot.cite.util are not used inside manubot.cite, but designed specifically for bibliography.py.

Our thought is that `manubot.cite` should contain all functionality that is primarily related to citations, references, and bibliographies. This includes things that are not needed at all for `standardize_citekey` and `citekey_to_csl_item`. Those two functions are not intended to be the sole user-facing aspect of the `manubot.cite` API. Thus far, we have expected users to import from submodules.

**Comment by epogrebnyak** [comment]
The development story makes sense - I suggest to look if dataclasses simplify life, if they do. I think `CiteKey` and `Handle` subclasses should be in `__init__.py` as well as some functions which are responsible for complex behaviour.

I close the issue, as the answer given in full. Maybe can refer to this issue if documentation in https://github.com/manubot/manubot/issues/117 goes ahead.
