### ISSUE TITLE
Question - was pypandoc considered as a dependency?

### ISSUE THREAD

**Issue by epogrebnyak** [manubot/manubot#163]
I thought about wrapping the work with a local installation of Pandoc into `Pandoc` class that provides a .run(args) method. 

Noticed there is a library called pypandoc, which does similar job of managing the invokation of pandoc.

 Was it ever considered as dependency? Any opinion on if it is worth using?

**Comment by dhimmel** [comment]
I remember looking at [pypandoc](https://github.com/bebraw/pypandoc), but didn't think it added much over just subprocess calls to pandoc. However, there were a few potential downsides:

1. the possibility that new pandoc features won't be accessible until pypandoc gets updated (which it hasn't in over 1.5 years based on commit log)
2. extra dependencies when no clear reason why we need it. The pandoc CLI API is already at a high level.
3. we have to configure pandoc's behavior very specifically. it takes more time if we have to learn another API that gets translated to the pandoc API, which is the API that we actually care about and is documented. Not sure it supports all the nuances we may need.

I think I may of tried it and concluded not sure why it's better than subprocess which gives us exactly the control we need, while making portable pandoc calls we can use outside of Python.

**Comment by epogrebnyak** [comment]
Strange they stalled at 2017 version, as pandoc is in demand, so should be a good python wrapper. 

I liked their fallback to reserve copy of pandoc and citeproc if not installation was found. It is a heavy binary depenedency though, that's why they needed `conda`. Just an observation.

Also gave me a thought it is possible to unify the calls to pandoc 
with a factory for CLI wrapper and Pandoc class with `run(args)` and `.version` method, a pseudocode:

```
def create_pandoc_controller(pandoc_path=None, pandoc_citeproc_path=None):
  # fail if no pandoc installed
  # return Pandoc instance on success
  pass

class Pandoc:

  @property
  def version(self):
    return (2, 0, 0) # return a tuple	

  def run(args):
    result = ... # subprocess call with capture_output=True
    return result.stdout, result.stderr
```
I
Pandoc class can also be useful in running the tests.
