### ISSUE TITLE
process: reconsider metadata and variables distinction

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#172]
Currently we have a function `get_metadata_and_variables` that returns two dictionaries (`metadata` and `variables`) that is called during `manubot process`:

https://github.com/manubot/manubot/blob/9023b7fbfa0b235c14a4d702516bc0cd6d3101ed/manubot/process/util.py#L170-L220

`metadata` is written as a yaml block at the start of [`manuscript.md`](https://github.com/manubot/rootstock/blob/1fcd2834c080116fe544c7a7187b5b6d8dedfb81/manuscript.md). Presently rootstock has the following `metadata`:

```yaml
author-meta:
- John Doe
- Jane Roe
date-meta: '2019-11-01'
keywords:
- markdown
- publishing
- manubot
lang: en-US
title: Manuscript Title
```

`variables` currently contains more stuff and is written to [`variables.json`](https://github.com/manubot/rootstock/blob/1fcd2834c080116fe544c7a7187b5b6d8dedfb81/variables.json):

<details>
<summary>variables.json</summary>

```json
{
  "date": "November 1, 2019",
  "authors": [
    {
      "github": "johndoe",
      "name": "John Doe",
      "initials": "JD",
      "orcid": "XXXX-XXXX-XXXX-XXXX",
      "twitter": "johndoe",
      "email": "john.doe@something.com",
      "affiliations": [
        "Department of Something, University of Whatever"
      ],
      "funders": "Grant XXXXXXXX",
      "affiliation_numbers": [
        1
      ]
    },
    {
      "github": "janeroe",
      "name": "Jane Roe",
      "initials": "JR",
      "orcid": "XXXX-XXXX-XXXX-XXXX",
      "email": "jane.roe@whatever.edu",
      "affiliations": [
        "Department of Something, University of Whatever",
        "Department of Whatever, University of Something"
      ],
      "affiliation_numbers": [
        1,
        2
      ]
    }
  ],
  "affiliations": [
    {
      "affiliation": "Department of Something, University of Whatever",
      "affiliation_number": 1
    },
    {
      "affiliation": "Department of Whatever, University of Something",
      "affiliation_number": 2
    }
  ],
  "ci_source": {
    "provider": "travis",
    "repo_slug": "manubot/rootstock",
    "repo_owner": "manubot",
    "repo_name": "rootstock",
    "commit": "7cf9071212ce33116ad09cf2237a370b180a3c35",
    "triggering_commit": "7cf9071212ce33116ad09cf2237a370b180a3c35",
    "build_url": "https://travis-ci.com/manubot/rootstock/builds/134602372",
    "job_url": "https://travis-ci.com/manubot/rootstock/jobs/251925838",
    "manuscript_url": "https://manubot.github.io/rootstock/v/7cf9071212ce33116ad09cf2237a370b180a3c35/"
  },
  "manuscript_stats": {
    "reference_counts": {
      "doi": 3,
      "isbn": 1,
      "pmcid": 1,
      "pmid": 1,
      "url": 1,
      "wikidata": 1,
      "total": 8
    },
    "word_count": 1363
  }
}
```

</details>

`variables` is used for the jinja2 templating while `metadata` is used for Pandoc's `yaml_metadata_block`. #138 is making us rethink this distinction, since it would like to access fields from both dictionaries.

**Comment by dhimmel** [comment]
Currently, the following fields in `metadata.yaml` are treated specially, rather than being passed through to Pandoc's yaml_metadata_block:

- author_info
- thumbnail

These fields are custom Manubot fields and are not passed through to the yaml_metadata_block in `manuscript.md`, although `author_info` is used to derive `author-meta` for pandoc. Pandoc supports [many metadata fields](https://pandoc.org/MANUAL.html#metadata-variables), hence why we pass-through all fields besides those above.

**Comment by dhimmel** [comment]
Proposal:

```yaml
pandoc:
- title: xxx
- date-meta: XXX
- author-meta: xxx
manubot:
- authors:
- date:
- thumbnail_url:
- affiliations:
# user_variables as well
```

**Comment by dhimmel** [comment]
https://github.com/manubot/manubot/pull/173 changed the implementation to the following:

https://github.com/manubot/manubot/blob/ebac7abd754015a5ec24a6fff39c35a72d4dffb0/manubot/process/util.py#L171-L183

But I'm not fully satisfied. The docs state "All fields from a manuscript's `metadata.yaml` are copied to [variables.pandoc]", but this is not true according to the implementation.

**Comment by dhimmel** [comment]
There are a few different parts of `metadata.yaml` that we have to decide how to handle:

1. top-level fields that manubot interprets and thus can handle them on a case-by-case basis
2. top-level fields that manubot does not interpret and thus must either discard or put somewhere.
3. fields under `pandoc`
4. fields under `manubot`

**Comment by dhimmel** [comment]
@agitter would you be able to take a look at https://github.com/manubot/manubot/pull/175. Specifically, the `load_variables` function and whether you think this processing pipeline makes the most sense. I'll keep the `load_variables` docstring in the PR up-to-date.

**Comment by agitter** [comment]
Yes, I'll review.  It may not be today.
