### ISSUE TITLE
Increase flexibility of citation syntax

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#192]
Now that we are close to having a working pandoc filter for citations in #99, I'm rethinking our citekey syntax. I think we can be more flexible and simplify the implementation considerably.

Consider the following markdown document for Pandoc:

```markdown
---
citekey-aliases:
  my-alias: https://openreview.net/forum?id=HkwoSDPgg
references:
  - id: my-citekey
    type: book
  - id: my-citekey-2
    type: article-journal
  - id: my-citekey-3
    type: article-journal
...
Here are a bunch of citations:

@my-alias
@my-citekey
@my-citekey-2
@doi:10.15363/thinklab.4
@doi:10/993
@pmcid:PMC4497619
@pmid:26158728
@arxiv:1508.06576v2
@isbn:9781339919881
@https://nyti.ms/1QUgAt1
@http://nyti.ms/1QUgAt1
@url:https://nyti.ms/1QUgAt1 (for backwards compatibility)
@wikidata:Q50051684

This citation is a valid persistent identifier, but it will be treated as an alias [@doi:10/992] because an alias is defined below.

[@doi:10/992]: my-citekey-3
```

1. find all citekey-aliases, as defined by either `metadata.citekey-aliases` or the `pandoc-url2cite` link-reference syntax
2. extract all citekeys (pandoc Citation elements in the AST)
3. extract all manual references from `metadata.references` and `metadata.bibliography` files
4. for each citekey:
   1. dealias if possible
   2. if citekey in manual references, break
   3. assume citekey is a persistent ID, standardize, and attempt to generate a CSL Item. if success, break
   4. if no metadata found, log a warning but leave citekey alone
5. if citekey is invalid according to pandoc syntax, shorten it and update Citations and references accordingly. 

Related issues:

- https://github.com/manubot/manubot/issues/114
- https://github.com/manubot/manubot/issues/123: while I'm not planning to immediately make source prefixes of persistent IDs optional, this workflow makes it considerably easier to do so.
- https://github.com/phiresky/pandoc-url2cite/issues/1: applies suggestion by @phiresky to interpret `http:` and `https:` as citation sources, so `url:` is not needed.
- https://github.com/manubot/manubot/issues/120: applies suggestion from @nichtich to support `metadata.citekey-aliases`.
- gets rid of `tag:` and `raw:` source prefix. A citekey is a "tag" if an alias is defined for it. A citekey is raw if it is not a supported persistent ID.

@agitter and others, what do you think?

**Comment by agitter** [comment]
Most of this makes sense to me and brings Manubot's citation processing more in line with related tools, which is desirable.

I don't really like allowing a valid persistent identifier to be used as an alias.  However, is that required to get rid of the `tag:` prefix?  Would we need to support `tag:` and `raw:` for a while for backwards compatibility?

> if citekey is invalid according to pandoc syntax

Can you clarify what that means?

**Comment by dhimmel** [comment]
> I don't really like allowing a valid persistent identifier to be used as an alias.

I don't expect this to occur frequently. Perhaps there are some valid uses, like replacing a preprint doi with the published version doi without having to change it in all places. Or redirecting a url temporarily until an intermittent error is fixed.

Another aspect of aliases I didn't consider is the following situation `{x: y, y: x}` or `{x: y, y: z}`. We could avoid these situations by only doing on de-aliasing step (the current implementation).

> Would we need to support `tag:` and `raw:` for a while for backwards compatibility?

Using `tag:my-tag` would be a regular citekey. If an alias was defined with a key `tag:my-tag`, then the `tag:my-tag` could be mapped to another citekey. `raw:my-raw` would not be treated specially. But since it wouldn't be a supported persistent identifier, the user would be expected to provide the reference metadata. If they didn't, pandoc-citeproc would insert `???` where the citation appears in the text. In this way, the syntax of `raw:` and `tag:` is backwards compatible... those citekeys will still work, but the program will not understand the `raw:` or `tag:` aspect.

Alternatively, we could require `tag:*` citekeys to have an alias. But I think that's unnecessary complexity.

> if citekey is invalid according to pandoc syntax

see https://github.com/jgm/pandoc/issues/6026 about how currently pandoc citekeys must conform to a specific syntax:

> Each citation must have a key, composed of '@' + the citation identifier from the database, and may optionally have a prefix, a locator, and a suffix. The citation key must begin with a letter, digit, or `_`, and may contain alphanumerics, `_`, and internal punctuation characters (`:.#$%&-+?<>~/`)

So if we de-alias to `paper=2015`, which is an invalid citekey, we need to shorten it.

**Comment by dhimmel** [comment]
Regarding how we support citekey-aliases, it appears pandoc supports `other-ids` in `references` as per https://github.com/jgm/pandoc-citeproc/issues/356 / https://github.com/jgm/pandoc-citeproc/commit/8326a10f93c1109105ddce01502b2da22f8e6445. Therefore, rather than mapping aliases ourselves, we could add aliases to references using `other-ids`. Although I'm not sure this is better because `other-ids` is not part of the CSL JSON spec.

**Comment by dhimmel** [comment]
In https://github.com/manubot/manubot/issues/218, we consider supporting all identifiers.org CURIEs, which would greatly expand the supported citekey prefixes.
