### ISSUE TITLE
Support identifier.org compact identifiers as citation keys

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#218]
_Originally posted by @dhimmel in https://github.com/manubot/manubot/issues/216#issuecomment-607332692_:

> But perhaps the best general solution would be accept any identifiers.org compact IDs (CURIEs). Then:
> 
> 1. make API call to https://resolver.api.identifiers.org/clinicaltrials:NCT04292899 to extract `compactIdentifierResolvedUrl`, in this case https://clinicaltrials.gov/ct2/show/NCT04292899.
> 2. Use translation-server to generate bibliographic metadata for the URL.

**Comment by dhimmel** [comment]
Here's an analysis of the current citation sources we support as per:

https://github.com/manubot/manubot/blob/db4c4771b30b08ce19209edfb1d0f819fef07a8b/manubot/cite/citekey.py#L20-L28

Are they supported at https://registry.identifiers.org/:

- `doi`: yes
- `pmid`: as `pubmed`
- `pmcid`: yes as `pmc`
- `arxiv`: yes
- `isbn`: yes
- `wikidata`: yes
- `url`: no, but we may want to migrate to `http` / `https` (also not supported)

For future citation key sources with special Manubot support, we probably should try to use the same prefix as identifiers.org when possible. We could deal with the special cases of `pmid` and `pmcid` pretty easily.

**Comment by cthoyt** [comment]
I'm using manubot for the first time and I've got lots of ChEBI references in my first paper. Would love to see this feature!

However, a step further than what's possible with identifiers.org is that I would like to just use the identifier, and have the name get resolved and inserted in the manuscript. Then, we'd be a step closer to *not* having to do NER as much

**Comment by dhimmel** [comment]
> I've got lots of ChEBI references in my first paper. Would love to see this feature!

Do you mean you'd like to cite specific compounds like `@CHEBI:53438` that would be expanded to cite https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:53438?

> I would like to just use the identifier, and have the name get resolved and inserted in the manuscript

Are you saying you'd like to just do `@53438` or `CHEBI:53438` or something else? Also do you want to create a citation & reference, or you'd like a way to use persistent IDs without a citation like:

> we used CHEBI:53438 to do the experiment

and have the rendered manuscript show

> we used [iron(3+) sulfate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:53438) to do the experiment

**Comment by agitter** [comment]
I'm also curious about @cthoyt's use case because it seems different from what I had in mind.  I would use this as:
```
We ran docking program X on the Mpro structure [@pdb:6LU7].

We clustered the expression data [@geo:GSE103322].
```

**Comment by cthoyt** [comment]
> Are you saying you'd like to just do `@53438` or `CHEBI:53438` or something else? Also do you want to create a citation & reference, or you'd like a way to use persistent IDs without a citation like:
> 
> ```gfm
> we used [CHEBI:53438] to do the experiment
> ```
> 
> and have the rendered manuscript show
> 
> > we used [iron(3+) sulfate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:53438) to do the experiment

I want exactly that! Of course the syntax is up to you.
