### ISSUE TITLE
Case sensitivity of citekey prefixes

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#226]
One of the updates in #223 is
> Prefixes are no longer case sensitive, although the standard form is lowercase.

Is that behavior working as intended?  I was testing the `manubot cite` command locally with version 7055bcc6524fdf1ef97d838cf0158973e2061595.  The prefix seems to require lowercase, which makes some CURIEs unusable:

```
$ manubot cite DOI:10.1021/acscentsci.0c00272
## ERROR
citekey sources should be all lowercase.
Should DOI:10.1021/acscentsci.0c00272 use "doi" rather than "DOI"?
[]
## CRITICAL
Failure: exiting with code 1 due to logged errors

$ manubot cite GO:0006915
## ERROR
citekey sources should be all lowercase.
Should GO:0006915 use "go" rather than "GO"?
[]
## CRITICAL
Failure: exiting with code 1 due to logged errors

$ manubot cite go:0006915
## ERROR
invalid go citekey: go:0006915
0006915 does not match regex ^GO:\d{7}$
[]
## CRITICAL
Failure: exiting with code 1 due to logged errors
```

**Comment by dhimmel** [comment]
https://github.com/manubot/manubot/pull/223 was only a partial migration to the new system. The in-progress #225 should address this.

**Comment by agitter** [comment]
Got it, thanks.
