### ISSUE TITLE
Process always adds rootstock as a remote

### ISSUE THREAD

**Issue by aarmey** [manubot/manubot#229]
I know this behavior is noted in `get_rootstock_commit()` but it seems surprising that a file processing tool would modify the users git repository. Also, I think it makes more sense when one has forked `rootstock`, but manubot has been useful in places where the files we're feeding in look nothing like `rootstock` 😀. Perhaps a behavior more consistent with expectations would be to check if `rootstock` is a remote, and only return the commit hash if it's found?

**Comment by dhimmel** [comment]
The guilty function:

https://github.com/manubot/manubot/blob/e18fed8cfb4c7fb9b5b39aa45bbba4aeadff6c9a/manubot/process/metadata.py#L180-L191

As far as I can tell, this is only called from 

https://github.com/manubot/manubot/blob/9c33b7a53f60aa5aba42424b925af0c32ea561fb/manubot/process/util.py#L194-L213

So this should only occur when the user is running `manubot process`.

> Also, I think it makes more sense when one has forked rootstock, but manubot has been useful in places where the files we're feeding in look nothing like rootstock

`manubot process` assumes to some degree it's running on a rootstock-derived repository. Can you explain a bit more about your use case?

In the longterm, we're trying to get rid of `manubot process` altogether and move to `manubot build` (prototype PR at https://github.com/manubot/manubot/pull/209). `manubot build` would not assume a rootstock-derived repo, and would work on any directory with the right files (i.e. `metadata.yaml` and markdown content). So will probably hold off until then to change things.

But understanding your use cases will help us ensure they're supported in future functionality.

**Comment by dhimmel** [comment]
> Perhaps a behavior more consistent with expectations would be to check if rootstock is a remote, and only return the commit hash if it's found?

The problem is that CI and github clones default to having no `rootstock` remote. We could add the remote on CI and add instructions for local users to add it. But I figure that's worse than adding a remote. From my quick search, it seemed unlikely to do anything destructive to add the remote, although perhaps it's puzzling to users to see.

**Comment by aarmey** [comment]
Oh great—`manubot build` should resolve this. You're right it does nothing destructive; it's just surprising to see.

[This repository](https://github.com/meyer-lab/ps-growth-model) is an example of our standard use case. We generally have a Python or Julia package alongside a manubot-built manuscript within a folder. In one case we have two separate manuscripts within a repository.

**Comment by dhimmel** [comment]
> We generally have a Python or Julia package alongside a manubot-built manuscript within a folder

Will take a look. Linking to your [makefile](https://github.com/meyer-lab/ps-growth-model/blob/3d1b53f4310de3ba42aa1db5847451be1642c5a8/makefile), which is an alternative to rootstock's `build.sh` it seems. The step that ends up adding the remote:

```make
output/manuscript.md: venv manuscript/*.md
	. venv/bin/activate && manubot process --content-directory=./manuscript/ --output-directory=./output --log-level=INFO
```
