### ISSUE TITLE
Integrate with Tina

### ISSUE THREAD

**Issue by slavakurilyak** [manubot/manubot#230]
**What is the limitation of manubot?**

Manubot requires technical knowledge or expertise [[1](https://greenelab.github.io/meta-review/#collaborative-writing-platforms)]. [Tina](https://tinacms.org/) is one way to overcome this limitation. 

**How does Tina work?**

Tina is an open-source website editing toolkit for React-based frameworks, i.e. [Next.js](url), [Gatsby](https://www.staticgen.com/gatsby), [UniJS](https://www.staticgen.com/umi), [React Static](https://www.staticgen.com/react-static), [Charge](https://www.staticgen.com/charge), [Cuttlebelle](https://www.staticgen.com/cuttlebelle), [Phenomic](https://www.staticgen.com/phenomic), [Antwar](https://www.staticgen.com/antwar), [Sitio](https://www.staticgen.com/sitio) or similar. Tina is a middleware between frontend and content source (i.e. Markdown) [[2](https://bejamas.io/blog/headless-cms/#tina)].

**What is the advantage of Tina over Github?**

Tina does not force website visitors to use or learn Github workflows. Tina provides a live-editing experience allowing website visitors to edit Manubot generated HTML. 

**What is the user experience of Tina?**

To view of demo of Tina, go [here](https://tinacms.org/) and click "Edit This Site". Manubot can follow a similar user experience by encouraging website visitors to edit hosted manuscripts.

**What is the requirement of Tina?**

Manubot uses Pandoc to [build](https://github.com/manubot/rootstock/tree/master/build) manuscripts. Tina relies on [static site generators](https://www.staticgen.com/), i.e. [JAMstack](https://jamstack.org/).

**Comment by dhimmel** [comment]
Looks cool. I'd like to try Tina out. I tried "Edit This Site", but the permissions requirement was way too broad for me to proceed: 

> ![image](https://user-images.githubusercontent.com/1117703/82731454-fecbf280-9cd4-11ea-83be-7d08b00f9b4c.png)

Is there a way to only give Tina access to the specific repo it needs access to?

**Comment by slavakurilyak** [comment]
@dhimmel Not that I'm aware of. I think you authorize Tina to access any public repository. Imagine there are hundreds or thousands of Tina-enabled React-based websites. Any React-based website hosted publically on Github could be Tina-enabled or contain live-editing functionality.
