### ISSUE TITLE
Consider Static Site Generators (SSGs)

### ISSUE THREAD

**Issue by slavakurilyak** [manubot/manubot#231]
[MDX](https://mdxjs.com/) is one way to make manuscripts more API-driven and allow for dynamic content. [Static site generators (SSGs)](https://www.staticgen.com/) are another. Learning English is one way to contribute to international research. i18n is another. 

SSGs [blur the lines between websites and apps](https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/) and [offer support for localization and internationalization (i18n)](https://www.gatsbyjs.org/docs/localization-i18n/). 

Inspiration: The United Nations recognizes [six working languages](http://ask.un.org/faq/14463) — Arabic, Chinese, English, French, Russian, and Spanish.

This issue is related to #230.

**Comment by dhimmel** [comment]
For the time being, we want Manubot to be as aligned as possible with Pandoc. Therefore, processing of input Markdown should be accomplished by Pandoc with additional functionality added via [Pandoc filters](https://pandoc.org/filters.html).

Thanks for the links. They're all interesting, but given our limited development time, we should focus on enhancements that have a pressing and clear application based on the current design of Manubot.
