### ISSUE TITLE
Wrong title for reference: ":{unav)"

### ISSUE THREAD

**Issue by miltondp** [manubot/manubot#239]
When I reference [this article](https://doi.org/10.1186/1471-2164-7-187) using `@doi:10.1186/1471-2164-7-187`, the title shown is `:{unav)`. This is how it gets rendered in HTML in the References section:

![image](https://user-images.githubusercontent.com/172687/83933330-90c40880-a775-11ea-9079-0338b9022c7c.png)

The same happens in the PDF output.

Thank you so much for this great tool! Let me know please if more details are necessary.

**Comment by miltondp** [comment]
Related issue: https://github.com/crosscite/content-negotiation/issues/102

**Comment by agitter** [comment]
Thanks for raising this issue @miltondp.  Would you like help with a workaround for this citation until the upstream content negotiation error is resolved?  That could take a while.

The workaround would be to switch to a PMID citation `@pubmed:16869964` or use a manual reference to override the title.

**Comment by miltondp** [comment]
Hi @agitter. Thanks so much for your help. I'm using the manual reference workaround (suggested by @dhimmel), but didn't know about the PMID one. I will give it a try!

**Comment by dhimmel** [comment]
Closing since this is an upstream issue

**Comment by vincerubinetti** [comment]
Can someone advise me on how to work around this for the [new Greenelab website](https://greenelab.github.io/greenelab.com/research). Do we know if there's a pattern to which references result in this error?

**Comment by dhimmel** [comment]
> Can someone advise me on how to work around this for the new Greenelab website.

Interesting. Looks like you're having the issue for the `container-title` rather than the `title`. 

> New Long-Term Memory Genes Revealed by Assessing Computational Function Prediction Methods
> Balint Z. Kacsoh,  Stephen Barton,  Yuxiang Jiang,  Naihui Zhou,  Sean D. Mooney,  Iddo Friedberg,  Predrag Radivojac,  Casey S. Greene,  Giovanni Bosco
> (:unav)  ·  01 Jan 2019
> 
> Sci-Hub provides access to nearly all scholarly literature
> Daniel S Himmelstein,  Ariel Rodriguez Romero,  Jacob G Levernier,  Thomas Anthony Munro,  Stephen Reid McLaughlin,  Bastian Greshake Tzovaras,  Casey S Greene
> (:unav)  ·  01 Mar 2018
> 
> Cross-platform normalization of microarray and RNA-seq data for machine learning applications
> Jeffrey A. Thompson,  Jie Tan,  Casey S. Greene
> (:unav)  ·  21 Jan 2016

And all 3 of those are different journals, so it's some large upstream issue.

A few options:

1. wait it out since this will probably be fixed upstream
2. keep track of your own `references.json` file where you include the CSL JSON for these references that are problematic. You can pass this to `manubot cite` with `--bibliography`.
3. switch the following line to `https://doi.org/` (not an option from the cite CLI, so probably won't work for you)

    https://github.com/manubot/manubot/blob/7055bcc6524fdf1ef97d838cf0158973e2061595/manubot/cite/doi.py#L123
