### ISSUE TITLE
Idea: use doc to store global variables in cite_filter

### ISSUE THREAD

**Issue by sergiocorreia** [manubot/manubot#254]
Looking at [cite_filter](https://github.com/manubot/manubot/blob/master/manubot/pandoc/cite_filter.py) I noticed the global global_variables. However, it's used only by functions with access to `doc`, so as an alternative you can always do `doc.something = 123` instead of `global_variables["something"] = 123`. You get rid of the global, and it's a bit cleaner.

**Comment by dhimmel** [comment]
@sergiocorreia thanks for the input. Here's some of the relevant code inline:

https://github.com/manubot/manubot/blob/01d69f066eaf6554111e6bcf197f7ee1fcfb240b/manubot/pandoc/cite_filter.py#L38-L40

It does appear that it'd make more sense to set these variables as attributes of doc. That is a more natural scope for the application as compared to a global module variable.

`doc` is an instance of [`panflute.elements.Doc`](https://github.com/sergiocorreia/panflute/blob/32fc99b6c07bb1296119fe8125648162cea282f0/panflute/elements.py#L27-L52).

I wonder if we should set all these custom attributes under something like `doc.custom` so we don't have to worry about attribute name collisions.

**Comment by sergiocorreia** [comment]
> I wonder if we should set all these custom attributes under something like `doc.custom` so we don't have to worry about attribute name collisions.

So far panflute only defines four attributes, doc.content, doc.metadata, doc.pandoc_version, and doc.pandoc_reader_options, so the likelihood of a collision is very low. But you can also keep everything under e.g. doc.manubot, for simplicity

**Comment by dhimmel** [comment]
> But you can also keep everything under e.g. doc.manubot, for simplicity

I like that since it provides a clear way for us to know what we've added from looking at a single attribute. Implemented in https://github.com/manubot/manubot/pull/255 along with type hints for the module.
