### ISSUE TITLE
Override for citation metadata on `pandoc-manubot-cite`

### ISSUE THREAD

**Issue by xihh87** [manubot/manubot#284]
Thanks a lot for this awesome software, it makes my life easier.

I've been having problems with some tricky URLs though (i.e. youtube) where information retrieval is incomplete. I'd like to have a way to override those tricky URLs and have `pandoc-manubot-cite` use the info I provide rather than downloading it incomplete.

I think this is a cheap fix where current retrievers can't get the full info.

**Comment by dhimmel** [comment]
> I should have reported this issue on manubot instead!

Not a problem. I transferred it to https://github.com/manubot/manubot/issues/284.

The `pandoc-manubot-cite` filter should support the following methods for specifying reference metadata manually:

- `bibliography` (path to file of manual references)
- `references` (CSL YAML references)
- `manubot-bibliography-cache` (path to file of cached references that is updated with automatically retrieved references)

Let us know if you encounter any problems. Otherwise, you can go ahead and close this issue if you've confirmed a solution.

**Comment by xihh87** [comment]
It seems that if I keep the note which says the reference comes from `manubot`, `pandoc-manubot-cite` overwrites.

The fix is to erase that note.

That should be documented, so others don't have a hard time figuring out.

**Comment by agitter** [comment]
@xihh87 can you please help me understand the problem better?  Are you saying that if the note field is still there in the manual reference entry the information you provided in the manual reference is ignored?  Or the information you provided for that manual reference is overwritten?

**Comment by xihh87** [comment]
When I need to correct the references I usually make them with:

```
manubot cite ref1 ... refn > bibliography.json
```

I change the information on `bibliography.json`, change the ids and **delete the NOTE fields** (if I don't do that, manubot uses the data it fetches from the internet).

Then I add to my markdown document:

```
---
[more fields]
bibliography: bibliography.json
---
```

The command I use for building the document is usualy something like this:

```
pandoc \
                -f ${FORMAT} \
                --filter=pandoc-manubot-cite \
                --filter=pandoc-citeproc \
                --pdf-engine=xelatex \
                -o ${target} \
                filename
```

The final document does contain the bibliography.

**Comment by xihh87** [comment]
@agitter the information provided manually is ignored.

**Comment by agitter** [comment]
Thanks for the clear explanation @xihh87.  I'll review why this happens and follow up to see whether the behavior should be better documented or modified.
