### ISSUE TITLE
index.html does not exist in the root gh-pages directory

### ISSUE THREAD

**Issue by adebali** [manubot/manubot#289]
In the manubot webpage documentation, the following information exists.

> HTML and PDF outputs are copied to the webpage directory, which is structured as static source files for website hosting.

The manuscripts using manubot have the index.html files as noted.

However, in my case, the index.html is not copied to the main directory in `gh-pages` branch which is automatically maintained through GitHub actions.

https://github.com/CompGenomeLab/lemur-manu/tree/gh-pages

All the up-to-date materials are available in `/v/latest`

What am I missing?

**Comment by agitter** [comment]
Because all manuscript outputs are versioned, the behavior is technically
> HTML and PDF outputs are copied to **a versioned subdirectory in** the webpage directory, which is structured as static source files for website hosting.

Nothing is added to the root directly on the `gh-pages` branch.

For your manuscript, https://github.com/CompGenomeLab/lemur-manu/tree/gh-pages/v/dddbb249d1305c38781e51d3cfa6f947fc609f38 has the latest version of these files and https://github.com/CompGenomeLab/lemur-manu/tree/gh-pages/v/latest is a symbolic link to that directory.

Should we clarify the documentation?

**Comment by adebali** [comment]
Thanks for the explanation @agitter 

So, the manuscript HTML is supposed to serve from https://compgenomelab.github.io/lemur-manu/v/freeze/ rather than https://compgenomelab.github.io/lemur-manu 

Is that correct?

**Comment by agitter** [comment]
The manuscript should be served from https://compgenomelab.github.io/lemur-manu.  Something may be broken with your repository.

`webpage/index.html`, etc. are symbolic links to the `latest` subdirectory (see the bottom of https://github.com/manubot/rootstock/pull/101/files).  Your `gh-pages` branch should have those symbolic links, which are present in [rootstock](https://github.com/manubot/rootstock/tree/gh-pages).  I'll have to look more closely at your repository to debug why they are missing.

**Comment by adebali** [comment]
Thank you.

Yes, since I wanted to use the latest version of manubot and accessory tools, I just copied the content from the old repository to the new rootstock template. I guess I reinitialized git :/

**Comment by agitter** [comment]
Your repository was missing the symbolic links from the rootstock repository that are needed to serve the manuscript from `gh-pages`.  I opened https://github.com/CompGenomeLab/lemur-manu/pull/1 to try to correct that.

If this pull request doesn't solve things, it may be easiest to start fresh and follow the setup instructions.  Then you could merge or copy in the current version of your manuscript content.

If you ever want to use a newer version of Manubot, you can follow the [rootstock update steps](https://github.com/manubot/rootstock/blob/main/SETUP.md#merging-upstream-rootstock-changes) or modify `build/environment.yml` to change the line
```
git+https://github.com/manubot/manubot@553090a16ac24a9fdc3f8df241a91b790c140865
```
to a newer Manubot commit.

**Comment by adebali** [comment]
This worked!
