### ISSUE TITLE
No way to stop manubot from adding rootstock remote

### ISSUE THREAD

**Issue by twrightsman** [manubot/manubot#290]
I use manubot in a subdirectory of a larger git repository and do not use the rootstock repository. It would be great if I could set a command-line flag or environment variable to tell manubot not to forcibly add the rootstock remote to my git repo. Would you be open to a pull request making this change? I currently have a patched manubot that does not add the remote but it would be nice if it were an upstream feature.

**Comment by dhimmel** [comment]
Thanks for the issue. Do you have CI build your manubot manuscript? Or is up to the users to build the manuscript inside the repo subdirectory? Is your repo public? If so it might be helpful to see.

Here's where the `rootstock` remote gets added:

https://github.com/manubot/manubot/blob/3ff3000f76dcf82a30694d076a4da95326e3f6ae/manubot/process/metadata.py#L195-L202

This is needed to compute `rootstock_commit`, which AFAICT is a debugging field at the moment and gets written to the output [`variables.json`](https://github.com/manubot/rootstock/blob/3fb3a2af232c6da4107074831b72122518fbcdac/variables.json#L85).

I agree that `manubot process` always setting the remote is too aggressive. Another user had this issue in https://github.com/manubot/manubot/issues/229.

We could make this opt-in, where perhaps rootstock-derived repos would opt-in by default? I'm open to hear other solutions?

**Comment by twrightsman** [comment]
Ah sorry, I didn't find that issue in my search before posting!
The repo is not public yet and I only build it manually, currently no plans for a CI build. It pretty much looks like the rootstock repository with a few files removed.
Reading the other issue, I can see why the remote needs to be added for CI purposes and it looks like `manubot build` will solve my use case when it's finished.
I think we can close this issue as a duplicate, since my use case of keeping related code with the manuscript has already been discussed in other issues.

**Comment by agitter** [comment]
Because `manubot build` doesn't have a timeline, I like the idea of adding a new `manubot process` command line flag that could disable adding the rootstock remote.  By default the flag would be set so that the remote is added, but advanced users would have more control to support custom use cases.

@dhimmel would a small pull request to add such a flag make sense to you?

**Comment by dhimmel** [comment]
> would a small pull request to add such a flag make sense to you?

Yes! Will reopen.

**Comment by agitter** [comment]
@twrightsman you mentioned that you
> currently have a patched manubot that does not add the remote

Are you interested in initiating a pull request?  We'll be happy to review and edit it with you.

**Comment by twrightsman** [comment]
@agitter Sure thing, I can create a pull request adding a command-line flag.
