### ISSUE TITLE
Switch from Identifiers.org to Bioregistry

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#305]
@cthoyt [mentionted](https://twitter.com/cthoyt/status/1442522899970154498) [Bioregistry](https://bioregistry.io/) as something that could be useful for Manubot.

Currently we use identifiers.org to define a list of CURIE prefixes that we can resolve, when used as citation keys. Bioregistry is more comprehensive (it is a superset of Identifiers.org), has an open contribution model on [GitHub](https://github.com/biopragmatics/bioregistry), and fixes a lot of issues.

There are two possible implementations:

1. The first is to replace the data in [`manubot/cite/curie/namespaces.json`](https://github.com/manubot/manubot/blob/11f7192e32aa280145e118135f0041a41a1b02d1/manubot/cite/curie/namespaces.json) with Bioregistry data. But [`bioregistry.json`](https://raw.githubusercontent.com/biopragmatics/bioregistry/main/src/bioregistry/data/bioregistry.json) has a different schema. @cthoyt is there a bioregistry data file with just the bioregistry-approved fields (like the top-level fields seen at https://bioregistry.io/api/registry/3dmet?format=yaml)?

2. using the `bioregistry` python package. This would require more work to implement but we could remove a lot of lines of code in favor of an upstream project! One concern is that there are [some dependencies](https://github.com/biopragmatics/bioregistry/blob/9278ec189f05d3b1d5669cf3127ba49988f54c26/setup.cfg#L47-L61).

**Comment by cthoyt** [comment]
I'll look back into making a slimmer version of the Bioregistry python package's requirements since some are only needed for updating the data

**Comment by cthoyt** [comment]
You might want to check the TSV export in https://github.com/biopragmatics/bioregistry/blob/main/docs/_dat/registry.tsv

**Comment by cthoyt** [comment]
As of https://github.com/biopragmatics/bioregistry/pull/235, there's now a nice JSON and YAML export with the consensus registry

**Comment by cthoyt** [comment]
I did #238 to remove some of the requirements from base install from the Bioregistry. Now the ones that remain are all pretty lightweight. I'm not sure if the issue was just that there were a lot of requirements, or from a different perspective. The ones that are left all have minimal requirements themselves (if any at all)
