### ISSUE TITLE
export in microsoft word or libreoffice format? 

### ISSUE THREAD

**Issue by aseedb** [manubot/manubot#314]
Is it possible to export the manuscript in microsoft office or in libreoffice format? Some collaborators are not familiar with github. I can share the PDF output with them but it is not the most convenient format if they are going to do some editing on the document.

**Comment by agitter** [comment]
Yes, it is possible to export the manuscript in the DOCX format.  There is some documentation in the [rootstock repository](https://github.com/manubot/rootstock/tree/main/build#building-the-manuscript)
> To build a DOCX file of the manuscript, set the BUILD_DOCX environment variable to true. For example, use the command BUILD_DOCX=true bash build/build.sh. To export DOCX for all CI builds, set an environment variable (see docs for GitHub Actions). Currently, equation numbers via pandoc-eqnos are not supported for DOCX output.

If you are using a recent version of Manubot rootstock, you can also run a single GitHub Actions workflow and select which optional output formats you want.  From the [Actions page](https://github.com/manubot/rootstock/actions/workflows/manubot.yaml) you can select the Manubot workflow and you'll see this button:
![image](https://user-images.githubusercontent.com/3532898/149381912-8d33d362-e6bb-477e-8808-b619f5c2fb2f.png)

**Comment by aseedb** [comment]
Very nice, thank you @agitter !
