### ISSUE TITLE
Accented character in ISBN citation

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#316]
I'm posting a user question sent by email:

> If I use "manubot cite" and one of the fields contains an accented character, then in the output the accented character is replaced by '??' (two question marks).
> 
> I am using manubot v0.5.1 (Python 3.8.9) from the command line using
iTerm2 (using LANG=en_US.UTF-8 encoding) on macOS 12.1.
Unfortunately, I am not a proficient Python programmer, so it would take me ages to find a solution myself.
> 
> For ISBN = 9789021537832 :
> 
> On WorldCat
https://www.worldcat.org/title/tarot-spiegel-van-jezelf/oclc/66186419&referer=brief_results
the Author name shows: Renée Maas.
> 
> Unfortunately, manubot cite replaces the 'é' by '??':
> 
```
$ manubot cite isbn:9789021537832
[
   {
     "id": "1HZWZsKBr",
     "type": "book",
     "abstract": "Beschrijving van een methode om zonder kennis van de tarot zelfinzicht te verkrijgen.",
     "event-place": "Utrecht",
     "ISBN": "9789021537832",
     "language": "Dutch",
     "note": "OCLC: 66186419\nThis CSL Item was generated by Manubot
v0.5.1 from its persistent identifier (standard_id).\nstandard_id: 
isbn:9789021537832",
     "publisher": "Kosmos-Z & K",
     "publisher-place": "Utrecht",
     "source": "Open WorldCat",
     "title": "De tarot: spiegel van jezelf",
     "title-short": "De tarot",
     "author": [
       {
         "family": "Maas",
         "given": "Ren??e"
       }
     ],
     "issued": {
       "date-parts": [
         [
           "2002"
         ]
       ]
     }
   }
]
```
> 
> Is there something to get UTF-8 output?
Am I missing something obvious?

**Comment by agitter** [comment]
I don't have an immediate answer to why this happened.  However, Manubot does support accented characters in general

```
$ manubot cite https://doi.org/10.1371/journal.pcbi.1005219
[
  {
    "id": "kSmk4noC",
    "type": "article-journal",
    "abstract": "De novo experimental drug discovery is an expensive and time-consuming task. It requires the identification of drug-target interactions (DTIs) towards targets of biological interest, either to inhibit or enhance a specific molecular function. Dedicated computational models for protein simulation and DTI prediction are crucial for speed and to reduce the costs associated with DTI identification. In this paper we present a computational pipeline that enables the discovery of putative leads for drug repositioning that can be applied to any microbial proteome, as long as the interactome of interest is at least partially known. Network metrics calculated for the interactome of the bacterial organism of interest were used to identify putative drug-targets. Then, a random forest classification model for DTI prediction was constructed using known DTI data from publicly available databases, resulting in an area under the ROC curve of 0.91 for classification of out-of-sampling data. A drug-target network was created by combining 3,081 unique ligands and the expected ten best drug targets. This network was used to predict new DTIs and to calculate the probability of the positive class, allowing the scoring of the predicted instances. Molecular docking experiments were performed on the best scoring DTI pairs and the results were compared with those of the same ligands with their original targets. The results obtained suggest that the proposed pipeline can be used in the identification of new leads for drug repositioning. The proposed classification model is available at http://bioinformatics.ua.pt/software/dtipred/.",
    "container-title": "PLOS Computational Biology",
    "DOI": "10.1371/journal.pcbi.1005219",
    "ISSN": "1553-7358",
    "issue": "11",
    "journalAbbreviation": "PLOS Computational Biology",
    "language": "en",
    "page": "e1005219",
    "source": "PLoS Journals",
    "title": "Computational Discovery of Putative Leads for Drug Repositioning through Drug-Target Interaction Prediction",
    "URL": "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005219",
    "volume": "12",
    "author": [
      {
        "family": "Coelho",
        "given": "Edgar D."
      },
      {
        "family": "Arrais",
        "given": "Joel P."
      },
      {
        "family": "Oliveira",
        "given": "José Luís"
      }
    ],
    "accessed": {
      "date-parts": [
        [
          "2022",
          1,
          18
        ]
      ]
    },
    "issued": {
      "date-parts": [
        [
          "2016",
          11,
          28
        ]
      ]
    },
    "note": "This CSL Item was generated by Manubot v0.5.2 from its persistent identifier (standard_id).\nstandard_id: url:https://doi.org/10.1371/journal.pcbi.1005219"
  }
]
```

**Comment by dhimmel** [comment]
The issue might be with the [Zotero Open WorldCat translator](https://github.com/zotero/translators/blob/d5b57d6b5dfe4c5b51c858f539201dca06c2a0c4/Open%20WorldCat.js). Will try to investigate more.

**Comment by agitter** [comment]
That's a good lead.  I visited https://www.worldcat.org/title/tarot-spiegel-van-jezelf/oclc/66186419&referer=brief_results and used the Zotero Connector for Chrome to import the reference into Zotero.  It uses the Open WorldCat translator for that.

It has the error in the author name:
![image](https://user-images.githubusercontent.com/3532898/150186252-c7d41843-9100-47ed-8a1a-585838d98f5b.png)

**Comment by dhimmel** [comment]
Nice @agitter do you want to post that on https://github.com/zotero/translators/issues?

**Comment by agitter** [comment]
I dug a little more, and it isn't a Zotero translator issue.  The translator scrapes the RIS file.  The RIS file has the corrupted characters.  I emailed OCLC support this message.

> When exporting citations with the “Export to EndNote / Reference Manager” button, some author names with accented characters are exported as ??.  For example, in https://www.worldcat.org/title/tarot-spiegel-van-jezelf/oclc/66186419&referer=brief_results and https://www.worldcat.org/title/numerologie/oclc/66494144&referer=brief_results the author name is “Renée Maas”.  The RIS file contains
> 
> A1  - Maas, Ren??e.,
> 
> Can you please assist with the corrupted citation data?

**Comment by agitter** [comment]
OLC Support wrote:

> Thanks for bringing this concern about the Endnote RIS export in the free Worldcat.org site to OCLC Customer support. That site is about to be replaced with an overhauled version that fixes a great deal of the current functionality so this is likely to be resolved in the next few months when the new version of the site comes out. 
> 
> They aren't fixing issues on the old site when we are so close to having the new site come out. I'm sorry for the inconvenience. 
> 
> Let me know if you have any questions. Thanks! 

We can check back periodically to see if the new site is live and then test the citation data once it is.

**Comment by xihh87** [comment]
So this issue should be closed, as:

- it is a source information error (not manubot's).
- it has been reported on the appropriate channel.

(I wanted to @ whomever reported the bug, but it's not here. Maybe we should reply letting them know.)

**Comment by dhimmel** [comment]
Will close since upstream but we can continue to comment. Looks like OCLC hasn't been updated yet:

```shell
curl --location --silent 'https://www.worldcat.org/oclc/66186419?page=endnote&client=worldcat.org-detailed_record'
```

```
TY  - BOOK
DB  - /z-wcorg/
DP  - http://worldcat.org
ID  - 66186419
LA  - Dutch
T1  - De tarot: spiegel van jezelf
A1  - Maas, Ren??e., 
PB  - Kosmos-Z & K
CY  - Utrecht
Y1  - 2002///
SN  - 9021537834 9789021537832
AB  - Beschrijving van een methode om zonder kennis van de tarot zelfinzicht te verkrijgen.
ER  - 
```
