### ISSUE TITLE
tutorial videos?

### ISSUE THREAD

**Issue by jessegmeyerlab** [manubot/manubot#322]
I'm noticing a few people who have very limited experience with github want to contribute. They are having a lot of trouble figuring out how to use manubot. This limits the pool of people who can contribute to a project. Have you experienced this in your projects? 

While I was on a zoom call with someone showing them how to make edits and then update those edits, they noted that it would be useful to have 'how to' videos. That way instead of teaching each person separately there are reusable resources. The main challenges I have seen so far are with to how to make contributions at all, and then how to update them according to edits and suggestions.

**Comment by jessegmeyerlab** [comment]
This is exactly what I was looking for. I will share these with the people that are struggling and let you know if there are areas that are not covered where people get tripped up.

**Comment by jessegmeyerlab** [comment]
Just brainstorming - and this would be a lot of work - but have you thought about moving the whole concept off github? It seems like github is a little clunky for writing. You could still use git in the background of a new web interface that is more designed for writing

**Comment by rando2** [comment]
@jessegmeyerlab so the back end really benefits from GitHub (because of the continuous integration features that allow us to do stuff like pull data directly from the internet to make figures!), but one thing I'm really interested in based on feedback from clinicians like @jbbyrd and others is whether we could link up with some sort of GUI that would allow people to edit the markdown files in their browsers in a way that would feel more like Google Docs. I have been meaning to talk to @agitter about this but I think in theory [https://stackedit.io](https://stackedit.io) would allow this -- except that it's been a bit buggy for me.

**Comment by byrdjb** [comment]
Ah, it translates markdown to html. I think writing in markdown will be unfamiliar & a real barrier to the vast majority of clinically savvy potential contributors, I'm sorry to say. I don't know whether there is a still more Google docs-like answer?
________________________________

**Comment by byrdjb** [comment]
I'm sure it says something slightly comical that I'm using email, not github to reply. 🙂

Thanks, Daniel. That makes sense, and the wish that it were trivially simple for clinicians is unrealistic in view of its development by the technically masterful principally for use by technically fluent user groups.
________________________________

**Comment by rando2** [comment]
@dhimmel hackmd.io does exactly what I've been looking for!!! Thank you so much!!! I think this will really help to teach git concepts without the syntax baggage that can be really tricky to pick up without help.

@byrdjb as someone who comes from evolutionary biology but keeps drifting further and further into technical spaces, I'm motivated to try to find a way to adapt Manubot for everyone (for my own purposes, wildlife biologists in particular) to use! This conversation is super helpful. I think the tool Daniel linked will let us do what you're looking for. I am a bit overwhelmed until the end of February but I will see if I can get a tutorial put together as soon as possible!

**Comment by byrdjb** [comment]
That's a promising development!
________________________________

**Comment by RLordan** [comment]
@rando2 I’d be happy to. To chime in on the previous discussion I had zero experience with github and I still fumble a bit but I actually like the formal layout for github with regards to the co-writing/reviewing with colleagues. Introduced me to something new too.
