### ISSUE TITLE
figures and legends

### ISSUE THREAD

**Issue by jessegmeyerlab** [manubot/manubot#323]
Sorry for posting so many issues. I am trying to add our first figure using the instructions here: https://github.com/manubot/rootstock/blob/main/USAGE.md#figures 

From this help text its not clear to my how to make it render the whole image and have the figure legend like I saw in the COVID review. Can someone please take a look here:

https://github.com/jessegmeyerlab/proteomics-tutorial/blob/main/content/05.peptide-protein-labeling.md

**Comment by dhimmel** [comment]
Linking to current image source in [`05.peptide-protein-labeling.md`](https://github.com/jessegmeyerlab/proteomics-tutorial/blob/7b1f9846d338ba55eb5231f0a70a511706c89fe9/content/05.peptide-protein-labeling.md?plain=1#L12-L24)

> the legend is there now but the figure edges are cutoff.

When I download the [`Summay_peptide-protein-labeling_.svg`](https://github.com/jessegmeyerlab/proteomics-tutorial/blob/7b1f9846d338ba55eb5231f0a70a511706c89fe9/content/images/Summay_peptide-protein-labeling_.svg), the edges are also cut off on my desktop SVG viewer. Perhaps the SVG `viewBox` is misconfigured?

Unrelated to the image being cutoff on the sides, Also noting the file size is a bit large at 2.7 MB. Not a major deal, but perhaps there is a raster element or something that is bloating it?

**Comment by jessegmeyerlab** [comment]
Thanks for your help.

When I download and view in internet explorer it looks like this: 
![image](https://user-images.githubusercontent.com/65188012/151570735-baeef687-4ee8-4103-915e-2691f717bf3b.png)

I'm not familiar with viewbox and raster elements - I will look into this

**Comment by agitter** [comment]
Closed by https://github.com/jessegmeyerlab/proteomics-tutorial/pull/18 and https://github.com/jessegmeyerlab/proteomics-tutorial/pull/22

Let us know if you run into any more figure issues.
