### ISSUE TITLE
manubot cite throwing JSONDecodeError on multiple DOI citations

### ISSUE THREAD

**Issue by slochower** [manubot/manubot#326]
I have noticed an uptick in `JSONDecodeErrors` on my internal manuscripts (I am seeing the errors while running `build/build.sh`; this is also reproducible by running `manubot cite` directly). I know there have been issues with CrossCite recently, but I'm afraid I haven't been following the discussion closely and I couldn't locate anything relevant after searching through both open and closed Issues (this does not appear related to #309, #310 or #319 to me).

I am seeing `JSONDecodeError` on >10 DOIs in my document. In this case, the actual citation looks reasonable to me. Here's an example:

```
(manubot) ~/rootstock ❯❯❯ manubot cite 10.1016/j.tips.2010.06.007                                                                                                ✘ 1
## ERROR
Error fetching metadata for doi:10.1016/j.tips.2010.06.007.
Invalid response from https://data.crosscite.org/10.1016/j.tips.2010.06.007:
The resource you are looking for doesn't exist.
## WARNING
Error in get_doi_csl_item_datacite for 10.1016/j.tips.2010.06.007 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
[
  {
    "publisher": "Elsevier BV",
    "issue": "10",
    "DOI": "10.1016/j.tips.2010.06.007",
    "type": "article-journal",
    "page": "449-454",
    "source": "Crossref",
    "title": "Drug–lipid interaction evaluation: why a 19th century solution?",
    "volume": "31",
    "author": [
      {
        "given": "Marta M.B.",
        "family": "Ribeiro"
      },
      {
        "given": "Manuel N.",
        "family": "Melo"
      },
      {
        "given": "Isa D.",
        "family": "Serrano"
      },
      {
        "given": "Nuno C.",
        "family": "Santos"
      },
      {
        "given": "Miguel A.R.B.",
        "family": "Castanho"
      }
    ],
    "container-title": "Trends in Pharmacological Sciences",
    "language": "en",
    "issued": {
      "date-parts": [
        [
          2010,
          10
        ]
      ]
    },
    "URL": "https://doi.org/dwqb8q",
    "container-title-short": "Trends in Pharmacological Sciences",
    "PMID": "20727600",
    "id": "ILgqnhdU",
    "note": "This CSL Item was generated by Manubot v0.5.2 from its persistent identifier (standard_id).\nstandard_id: doi:10.1016/j.tips.2010.06.007"
  }
]
## CRITICAL
Failure: exiting with code 1 due to logged errors
```

Other examples:
- 10.1021/acs.jctc.8b00046
- 10.1021/acs.jcim.8b00825

Edit: I'm using `manubot` version 0.5.2.

Edit 2: I tried using the example citations in the README and also see errors. Can someone else confirm this?

```
(manubot) ~/rootstock ❯❯❯ manubot cite --format=markdown \                                                                                                       ✘ 1
  doi:10.1098/rsif.2017.0387 pubmed:29424689 pmc:PMC5640425 arxiv:1806.05726

## ERROR
Error fetching metadata for doi:10.1098/rsif.2017.0387.
Invalid response from https://data.crosscite.org/10.1098/rsif.2017.0387:
The resource you are looking for doesn't exist.
## WARNING
Error in get_doi_csl_item_datacite for 10.1098/rsif.2017.0387 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
1. **Opportunities and obstacles for deep learning in biology and medicine**
Travers Ching, Daniel S Himmelstein, Brett K Beaulieu-Jones, Alexandr A Kalinin, Brian T Do, Gregory P Way, Enrico Ferrero, Paul-Michael Agapow, Michael Zietz, Michael M Hoffman, … Casey S Greene *Journal of The Royal Society Interface* (2018-04) <https://doi.org/gddkhn>
DOI: [10.1098/rsif.2017.0387](https://doi.org/10.1098/rsif.2017.0387) · PMID: [29618526](https://www.ncbi.nlm.nih.gov/pubmed/29618526) · PMCID: [PMC5938574](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5938574)

2. **Sci-Hub provides access to nearly all scholarly literature.**
Daniel S Himmelstein, Ariel Rodriguez Romero, Jacob G Levernier, Thomas Anthony Munro, Stephen Reid McLaughlin, Bastian Greshake Tzovaras, Casey S Greene *eLife* (2018-03-01) <https://www.ncbi.nlm.nih.gov/pubmed/29424689>
DOI: [10.7554/elife.32822](https://doi.org/10.7554/elife.32822) · PMID: [29424689](https://www.ncbi.nlm.nih.gov/pubmed/29424689) · PMCID: [PMC5832410](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5832410)

3. **Systematic integration of biomedical knowledge prioritizes drugs for repurposing**
Daniel Scott Himmelstein, Antoine Lizee, Christine Hessler, Leo Brueggeman, Sabrina L Chen, Dexter Hadley, Ari Green, Pouya Khankhanian, Sergio E Baranzini *eLife* (2017-09-22) <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5640425/>
DOI: [10.7554/elife.26726](https://doi.org/10.7554/eLife.26726) · PMID: [28936969](https://www.ncbi.nlm.nih.gov/pubmed/28936969) · PMCID: [PMC5640425](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5640425)

4. **Generalization of the Fermi Pseudopotential**
Trang T Le, Zach Osman, DK Watson, Martin Dunn, BA McKinney *arXiv* (2019-05-01) <https://arxiv.org/abs/1806.05726>
DOI: [10.1088/1402-4896/ab0811](https://doi.org/10.1088/1402-4896/ab0811)
## CRITICAL
Failure: exiting with code 1 due to logged errors
```

**Comment by dhimmel** [comment]
For your manuscripts, do you have the latest rootstock commit https://github.com/manubot/rootstock/commit/9a22fab4497f80f501ea361d028f26888ad9d5a0? `get_doi_csl_item_datacite` should no longer be called, since it no longer works for Crossref DOIs.

> I'm using manubot version 0.5.2.

We should release v0.5.3 with the fixes, but note that rootstock pins to a commit hash not version number. I'll release v0.5.3 after we merge https://github.com/manubot/manubot/pull/324, which itself is waiting on an upstream PR, but shouldn't be long.

**Comment by slochower** [comment]
> We should release v0.5.3 with the fixes, but note that rootstock pins to a commit hash not version number. I'll release v0.5.3 after we merge https://github.com/manubot/manubot/pull/324, which itself is waiting on an upstream PR, but shouldn't be long.

I am trying with a fresh clone of `rootstock`. I have https://github.com/manubot/rootstock/commit/9a22fab4497f80f501ea361d028f26888ad9d5a0 which installs https://github.com/manubot/manubot/commit/90925eeff90e3aaacaa504fc9a47107609cffc17.

**Comment by dhimmel** [comment]
> Forcing a rebuild of the env using conda env update --file build/environment.yml does seem to (1) upgrade

An yes, perhaps we can be more clear about that in the upgrade instructions (that you should upgrade your local conda environment if its changed).

**Comment by slochower** [comment]
Ah shoot. I get a different JSONDecodeError now. This is happening for multiple citations–will have more time to debug in a few days.

```
shortDOI lookup failed for 10.1124/mol.118.115113
Traceback (most recent call last):
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/site-packages/manubot/cite/doi.py", line 108, in get_short_doi_url
    response = requests.get(url, headers=headers).json()
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by Srishtiginjala** [comment]
I think I am also facing the same issue of JSONDecodeError on all DOI citations. I ran "./build.sh" and got a 404. All 14  DOI files have failed.
![Screenshot from 2022-02-20 10-42-52]
(https://user-images.githubusercontent.com/56593893/154829361-ec6b191e-ac09-4efe-94aa-f86a31e798ca.png)

**Comment by agitter** [comment]
I was able to run `manubot cite doi:10.1124/mol.118.115113` from the command line successfully with manubot https://github.com/manubot/manubot/commit/90925eeff90e3aaacaa504fc9a47107609cffc17 today.  Based on the location of the error, maybe this was an intermittent problem with http://shortdoi.org?

I'm not sure why this error isn't caught here in `get_short_doi_url`
https://github.com/manubot/manubot/blob/3551decae866dea6bfc548033469babfec0c6c31/manubot/cite/doi.py#L112-L114

**Comment by slochower** [comment]
> I was able to run manubot cite doi:10.1124/mol.118.115113 from the command line successfully with manubot https://github.com/manubot/manubot/commit/90925eeff90e3aaacaa504fc9a47107609cffc17 today.

I agree, I can run that too. It looks like now I'm getting a disconnect between `manubot cite` and running `bash build/build.sh`. I still see many `JSONDecodeError`s when building the manuscript, even for DOIs where `manubot cite <doi>`  looks good. Same exact environment for both.

![image](https://user-images.githubusercontent.com/5393995/154856100-6d815283-d1a9-42d2-ac7b-b45c13a0fe05.png)

**Comment by agitter** [comment]
I wasn't able to reproduce this in a test build on GitHub Actions.  I created https://github.com/agitter/my-manuscript/pull/21, which adds two of the DOIs we've discussed here.  It uses the latest rootstock.  I don't see these warnings in the [build log](https://github.com/agitter/my-manuscript/runs/5266431898?check_suite_focus=true) with or without the `doi:` prefix.

That could indicate the conda environment didn't update properly.  I added a new step to the workflow called "Dump conda environment" so we could debug any differences between the GitHub Actions environment and your local environment.

**Comment by slochower** [comment]
Hm, yes. We have the same Python, `manubot`, `pandoc`, and `jsonschema` versions. I'm not sure what other packages would be relevant. Other than that, there are some minor differences because I'm on a Mac.

**Comment by agitter** [comment]
This is tricky to debug because there are no obvious environment differences and we can't reproduce the problem in a GitHub Actions build.  My best thought right now is to create a manubot branch that adds additional logging and debugging code so we could better inspect what is happening inside `get_short_doi_url`.

@dhimmel do you any other ideas about how to probe why the cite filter behavior is different from the cite command?

**Comment by Srishtiginjala** [comment]
Yeah, even I can run that too and I am already using v0.5.2.

Thanks & Regards
Srishti

**Comment by slochower** [comment]
@agitter mind checking this one now?

```bash
(manubot) ~ ❯❯❯ manubot cite 10.1016/j.trechm.2020.11.004 --txt
## WARNING
shortDOI lookup failed for 10.1016/j.trechm.2020.11.004
Traceback (most recent call last):
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/site-packages/manubot/cite/doi.py", line 108, in get_short_doi_url
    response = requests.get(url, headers=headers).json()
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/slochowe/anaconda3/envs/manubot/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by agitter** [comment]
That DOI worked for me locally and in a GitHub Actions workflow: https://github.com/agitter/my-manuscript/runs/5339871080?check_suite_focus=true#step:8:12

I'm really curious what the `response` is in
```python
response = requests.get(url, headers=headers).json()
```

**Comment by slochower** [comment]
Hm, right. The response is code 200. Now let me look at `response.text`.

Oh.

Oh dear.

Oh, I see what's going on.

```
(manubot) ~ ❯❯❯ manubot cite 10.1016/j.trechm.2020.11.004

<!DOCTYPE html>
<html>
<center>
<img src="http://XXX/UserCheck/images/interactions/%7BE64E3494-E897-42F8-A902-9D94AD06DAA5%7D.png"></img><br><br>
<img src="http://XXX/UserCheck/img/block.png"></img><br>

<h2 style="text-align: center;"><span style="color: #ff0000;"><strong>PAGE BLOCKED</strong></span></h2>
<table style="height: 230px; width: 81.2144%; border-collapse: collapse; margin-left: auto; margin-right: auto;" border="0">
<tbody>
<tr>
<td style="width: 100%;">
<h2 style="text-align: left;">In compliance with Vertex's information security policy, access to this web site has been blocked. However, if there is a business need to access this site please open a ServiceNow ticket or call the Service Desk. Please include in the ticket, a business justification - why you must have access to this site, and the approval from your manager, e.g. ServiceNow approval or a copy of an email with your manager&rsquo;s approval.</h2>
</td>
</tr>
</tbody>
</table>
</html>
```

(Which is a little weird because it's not actually blocked, but...)

**Comment by agitter** [comment]
Great, that's some major progress to understanding what was different about your local builds.

Is there anything Manubot should do differently when these unexpected responses are encountered?  It looks like it logs a warning but does not kill the build, which seems appropriate to me.
