### ISSUE TITLE
Manubot unable to locate DOI's to post on the website

### ISSUE THREAD

**Issue by Srishtiginjala** [manubot/manubot#327]
I am trying to generate DOI's using Manubot to post our publications on the web. But when I run the build.sh file, all the 14 DOI's have failed critically and I got a 404 error. The requested resources weren't found and there is a JSONDecodeError also.

![Screenshot from 2022-02-20 10-42-52](https://user-images.githubusercontent.com/56593893/154829361-ec6b191e-ac09-4efe-94aa-f86a31e798ca.png)

**Comment by agitter** [comment]
Does your issue seem related to the discussion in #326?  What version of Manubot are you using?  Note that as discussed in https://github.com/manubot/manubot/issues/326#issuecomment-1046134508 the latest release on PyPI does not yet incorporate all the recent DOI citation updates.

After updating manubot with
```
$ pip install git+https://github.com/manubot/manubot@90925eeff90e3aaacaa504fc9a47107609cffc17 --upgrade
```

 I was able to extract metadata from your example DOI:
```
$ manubot cite doi:10.1038/nbt.4113
[
  {
    "publisher": "Springer Science and Business Media LLC",
    "issue": "4",
    "DOI": "10.1038/nbt.4113",
    "type": "article-journal",
    "page": "369-371",
    "source": "Crossref",
    "title": "Involving undergraduates in genomics research to narrow the education–research gap",
    "volume": "36",
    "author": [
      {
        "given": "Serghei",
        "family": "Mangul"
      },
      {
        "given": "Lana S",
        "family": "Martin"
      },
      {
        "given": "Eleazar",
        "family": "Eskin"
      }
    ],
    "container-title": "Nature Biotechnology",
    "language": "en",
    "issued": {
      "date-parts": [
        [
          2018,
          4
        ]
      ]
    },
    "URL": "https://doi.org/ghqfdv",
    "container-title-short": "Nat Biotechnol",
    "PMID": "29621227",
    "id": "9xL0SJJT",
    "note": "This CSL Item was generated by Manubot v0.5.2 from its persistent identifier (standard_id).\nstandard_id: doi:10.1038/nbt.4113"
  }
]
```

**Comment by agitter** [comment]
@Srishtiginjala is this example running locally or in a GitHub repository?  If it is in a repository running on GitHub Actions, I may be able to look more closely to help diagnose the problem.

**Comment by Srishtiginjala** [comment]
Hello Sir

It was on my local machine. But the issue seems to be resolved now.  The
manubot is running successfully on my desktop without any issues.

Thanks and Regards
Srishti

**Comment by agitter** [comment]
Great, glad to hear it is working now.
