### ISSUE TITLE
Upgrade CSL Schema to v1.0.2

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#352]
CSL schema version 1.0.2 was officially released on 2022-01-01: [github](https://github.com/citation-style-language/schema/releases/tag/v1.0.2) & [discourse announcement](https://discourse.citationstyles.org/t/announcing-csl-1-0-2-release-january-1-2022/1744).

**Comment by dhimmel** [comment]
Noting the hardcoded link to the CSL schema we're using:

https://github.com/manubot/manubot/blob/4283d792e60bc3280991e85fa2130a1d18a4bdfd/manubot/cite/citeproc.py#L23

**Comment by dhimmel** [comment]
Here's a [list of commits](https://github.com/dhimmel/csl-schema/compare/19596ab022f220de1239559400b31ee1ef9dc2ad...citation-style-language:schema:v1.0.2) that would be added by fast-forwarding `dhimmel/csl-schema:manubot` (https://github.com/dhimmel/csl-schema/commit/19596ab022f220de1239559400b31ee1ef9dc2ad) to `citation-style-language/schema:v1.0.2` (https://github.com/citation-style-language/schema/commit/506040022f6c37846343edd36658b23e85b5b8ff).

**Comment by dhimmel** [comment]
Following up on https://github.com/manubot/manubot/issues/296#issuecomment-1328050904, even with e14df43c0906b0d2ab7d54e50048887975198445, `manubot cite https://github.com/citation-file-format/ruby-cff` is returning type book.

**Comment by agitter** [comment]
@dhimmel I tested this again in https://github.com/manubot/manubot/issues/296#issuecomment-1426511834 after the translation server updates and `manubot cite https://github.com/citation-file-format/ruby-cff` now returns type software.
