### ISSUE TITLE
date-specific Wikipedia URL is not parsed correctly§

### ISSUE THREAD

**Issue by habi** [manubot/manubot#366]
For a manuscript we've cited a date-specific Wikipedia page as `[@https://en.wikipedia.org/w/index.php?title=Nrrd&oldid=1085264080]`.
The [rendered version](https://habi.github.io/EAWAG-manuscript/v/a9633de5317eab4c8df584555033c6c11e4d89c5/) of the manuscript displays this as `[22, =Nrrd&oldid=1085264080]` and links to https://en.wikipedia.org/w/index.php?title=Main_Page&oldid=1114291180

The link should be correctly be parsed and not be split at the '='.

**Comment by dhimmel** [comment]
From [usage](https://github.com/manubot/rootstock/blob/main/USAGE.md#citations):

> If a citation key does not fully match [this online regex](https://regex101.com/r/mXZyY2/latest) (for example, contains characters such as `;` or `=` or end with a non-alphanumeric character such as /), make sure to surround it with curly braces or use the [citation aliases](https://github.com/manubot/rootstock/blob/main/USAGE.md#citation-aliases) workaround below.

So you should be able to do the following as of Pandoc 2.14:

```
[@{https://en.wikipedia.org/w/index.php?title=Nrrd&oldid=1085264080}]
```

**Comment by habi** [comment]
Thanks for the pointer and solution.
In the end I [fixed the issue](https://github.com/habi/EAWAG-manuscript/commit/1d29c80e249cc5c922e4425f12fbd1cc723abde9) with a better citation ;)
