### ISSUE TITLE
Pin pyrate limiter version or upgrade to 3.0.0

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot#367]
I recently ran into this error with Lab Website Template. One specific citation with Manubot was failing:

```
Processing source 297 of 307, id: pubmed:29218914
## WARNING
Generating csl_item for 'pubmed:29218914' failed due to a ImportError:
cannot import name 'RequestRate' from 'pyrate_limiter' (/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyrate_limiter/__init__.py)
    Using Manubot to generate citation
            Couldn't parse Manubot response
```

Thanks to @falquaddoomi for helping me troubleshoot, it looks like the pyrate-limiter package very recently released a new major version which perhaps renames the RequestRate import or something. Version 2.10 of the package was previously working for me.

**Comment by dhimmel** [comment]
> Probably just easiest to require pyrate-limiter >= 3.0.

Actually pyrate-limiter 3 includes many changes and doesn't yet support context manager usage. Will require pyrate-limiter < 3

**Comment by jamesmhbarry** [comment]
Also have the same issue. How to resolve it?

**Comment by jamesmhbarry** [comment]
> @jamesmhbarry where are you encountering the error? Is this through a Manubot rootstock-based manuscript, direct use of the Manubot Python package, the lab website template, or something else? The solution to use the updated Manubot package that pins the version of pyrate-limiter will be somewhat different for each of these, and we can direct you appropriately.

I am trying to use the [requests-ratelimiter](https://github.com/JWCook/requests-ratelimiter) package, but the error comes up right at the beginning when calling 

`from requests_ratelimiter import LimiterAdapter
`

**Comment by dhimmel** [comment]
> I am trying to use the [requests-ratelimiter](https://github.com/JWCook/requests-ratelimiter) package

Ah so you're not using Manubot at all? This issue is only for when this error occurs when using manubot. You can look how we addressed it in https://github.com/manubot/manubot/pull/368
