### ISSUE TITLE
reference format?

### ISSUE THREAD

**Issue by jessegmeyerlab** [manubot/manubot#371]
Is the reference format editable? The journal is asking for page numbers and we have about 900 references so hoping to automate this

**Comment by agitter** [comment]
Yes, you can change this. See the rootstock usage section about custom formatting and changing the Citation Style Language file https://github.com/manubot/rootstock/blob/main/USAGE.md#custom-formatting.

**Comment by jessegmeyerlab** [comment]
thanks Tony

**Comment by jessegmeyerlab** [comment]
I see the csl example but need one from zotero - would this url be valid or I need to find the link to the csl behind this? 

https://www.zotero.org/styles?q=id%3Ajournal-of-proteome-research

**Comment by jessegmeyerlab** [comment]
sorry nvm I was able to download and put in the assets folder

**Comment by dhimmel** [comment]
I think the source CSL might is likely defined at <https://github.com/citation-style-language/styles/blob/533890226e8abbbeb31cd63a5b1180ffc6e4870d/dependent/journal-of-proteome-research.csl>
