### ISSUE TITLE
URL to citation

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#61]
In https://github.com/kipoi/website/issues/77 @dhimmel and @Avsecz discussed a potential new Manubot feature.  Per @dhimmel:
> One potential Manubot feature that could be helpful would be "URL to citation" that could perform the following conversion:

> https://doi.org/10.1101/gr.227819.117 ⟶ doi:10.1101/gr.227819.117
http://dx.doi.org/10.1101/gr.227819.117 ⟶ doi:10.1101/gr.227819.117
https://doi.org/gd54x8 ⟶ doi:10.1101/gr.227819.117
https://arxiv.org/pdf/1603.09123.pdf ⟶ arxiv:1603.09123

> Would also hopefully work with other types of URLs.

**Comment by dhimmel** [comment]
There are two possible features that may be useful:

1. reformatting URLs to be citation stings, as shown above. In these cases, the URLs always contain the citation identifier, but just need the identifier to be extracted and reformatted.
2. returning a list of citation strings that would cite the work referred to by the URL.

For the second, passing the URL `https://peerj.com/articles/705/` would return the following list:

0. `doi:10.7717/peerj.705`
1. `pmcid:PMC4304851`
2. `pmid:25648772`
3. `url:https://peerj.com/articles/705/`

I ordered the list by manubot's citation-source preference.

The http://kipoi.org/ use case of using Manubot to get authors for a URL reference would probably be OKAY with either method.

Chime in if you think either method would be useful... we probably won't pursue this unless there is some user interest.

**Comment by Avsecz** [comment]
For Kipoi, the both features are useful. Second one could be used for displaying the number of papers citing the model on the website (and maybe even link to a page where these papers are listed).

For the start, I think supporting URLs from doi, pubmed, arxiv and bioarxiv would be enough as these cover a broad spectrum. One can start with the functions I wrote for the website: https://github.com/kipoi/website/blob/master/app/models/authors.py#L6
