### ISSUE TITLE
shortDOI citation support

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#92]
Supporting citations of shortDOIs could be a nice feature. I see the major benefits as saving characters for excessively long DOIs and enabling a way to directly cite DOIs with forbidden characters such as `10.1016/S0933-3657(96)00367-3`. At least one user has attempted this workaround in https://github.com/Benjamin-Lee/deep-rules/pull/117/commits/c76ee4d20fa3f45935194b43b495b8159cbd30b4 / https://github.com/Benjamin-Lee/deep-rules/pull/117#issuecomment-456227977.

It seems like we could support a few different syntaxes:

1. `@doi:10/b6vnmd`
2. `@doi:b6vnmd`
3. `@shortdoi:b6vnmd`
4. `@shortdoi:10/b6vnmd`

I didn't see much shortDOI documentation online, but there is some provided when viewing a [shortened DOI result](http://web.archive.org/web/20190123160439/http://shortdoi.org/10.1016/S0933-3657(96)00367-3)

```
Your request was processed. The previously-created shortcut for 10.1016/S0933-3657(96)00367-3 is the handle:
10/b6vnmd
The shortcut HTTP URI is:
http://doi.org/b6vnmd
This shortcut will return the same results as http://dx.doi.org/10.1016/S0933-3657(96)00367-3, and doi:10/b6vnmd can be used in place of doi:10.1016/S0933-3657(96)00367-3.
```

Given the documentation, it seems that option 1 is the most canonical method. However, method 3 & 4 could help avoid user confusion.

***

Note that DOI content negotiation for crossref DOIs appears to work:

```
curl --location --header "Accept: application/vnd.citationstyles.csl+json" https://doi.org/b6vnmd
```

**Comment by dhimmel** [comment]
@bwiernik I saw your [zotero-shortdoi tool](https://github.com/bwiernik/zotero-shortdoi), and was wondering if you knew whether there was a lightweight API call that supports converting from shortDOIs to full DOIs? It looks like the DOI content negotiation calls above will work, but they return too much information. For efficiency, we'd like a way to just lengthen a shortDOI and nothing else.

**Comment by bwiernik** [comment]
The shortDOI API does not accept shortDOIs themselves, so you need to use the standard doi.org API. For example: 
https://doi.org/api/handles/10/b6vnmd

This results in a short JSON response with two slots. The first has information on the shortDOI. The second will contain the long DOI:
```
var url = 'https://doi.org/api/handles/10/b6vnmd';
var req = new XMLHttpRequest();
req.open('GET', url, true);
req.responseType = 'json';
var longDOI = req.response.values["1"].data.value;
```

Code addressing the various response values is here: https://github.com/bwiernik/zotero-shortdoi/blob/32a28d7803ac95e57ecf28f83857cfa32af594b3/chrome/content/scripts/zoteroshortdoi.js#L428

In terms of supporting shortDOI formats, only the `10/b6vnmd` form will work. The handle with `10/` is the actual "shortDOI". While the URL `https://doi.org/b6vnmd` will resolve, it won't work with the API. Just the part of the handle after `10/` is arbitrary text, so it also can't be pre-checked to determine if it is a validly-formatted DOI using regex (`/10\/[^\s]*[^\s\.,]/`). You could assume that any text stored as a DOI that does not match that regex is a shortDOI without the `10/` prefix and add it yourself, but that might open you up to a lot of invalid traffic. 

If you retrieve and store shortDOI handles yourself, I strongly recommend storing them and generating DOI URLs from them including the `10/` prefix. DOI links resolve with the prefix, and it makes it clearer that the handle is in fact a DOI.

**Comment by dhimmel** [comment]
Thanks @bwiernik. I didn't know about the DOI [Proxy Server REST API](https://www.doi.org/factsheets/DOIProxy.html#rest-api) (i.e. `doi.org/api/handles`). That will come in handy.

> The handle with `10/` is the actual "shortDOI"

Okay we will require users to include `10/` when working with shortDOIs and we will store shortDOIs with the `10/` prefix. I am conflicted however when it comes to shortDOI URLs. Currently, we omit `10/` in shortDOI URLs like `https://doi.org/b6vnmd` ([example](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/#ref-PZMP42Ak)), because it's nice for shortened URLs to be as short as possible. I see how this can lead to some user confusion however.
