### ISSUE TITLE
Manubot logo

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot#98]
I have sketches here for a manubot logo. Showed them to @dhimmel, and we have our preferences, but we'd like to get the input of others. I'm not a graphic designer per se, but I've picked up some knowledge about logo best practices:

- it should be simple, not too ornate or complex
- a child should be able to draw the gist of it
- it should work well with text or without text
- it should work well as a favicon (small icon size)
- it should work well in monochrome/print
- ideally, it should convey some of the meaning behind the product and give some indication of what it is, what it does, or what general industry it belongs to

![desktop](https://user-images.githubusercontent.com/8326331/52877904-5f12d280-3129-11e9-9e58-9fd66460f290.png)

These are just hand sketches, of course. Once we pick one, I'll translate it into a better looking vector format. We can also combine some of these ideas with each other, such as having the folded "paper" looking M in between the -\<M\>- idea.

I looked through the meta review for keywords that represented the project as a whole, such as edit, collaborate, ideas, version control, code, manuscript, document, writing, etc. For some inspiration, I looked at font-awesome icons related to these keywords, such as the following icons:

![icons](https://user-images.githubusercontent.com/8326331/52877907-6043ff80-3129-11e9-8e04-526d7d00e535.png)

Naturally, I think a real logo designer who is an expert in that specific field could do a better job, but a truly good one would be quite expensive.

**Comment by vincerubinetti** [comment]
Font choices for text:

![font choices](https://user-images.githubusercontent.com/8326331/52880224-6210c180-312f-11e9-92b8-3f77d745de47.png)

**Comment by ben-heil** [comment]
I like the brackets with the M inside, but it took a second to tell it was a robot. The logo could be something more humanoid and use the M as a mustache/mouth
![img_20190215_152303](https://user-images.githubusercontent.com/15317110/52893921-b89df000-316f-11e9-8d97-0eabfe7561bd.jpg)

**Comment by agitter** [comment]
Great choices!  I'm still considering which are my favorites.  The colored M and M with a black cube behind it look a little to much like the Gmail logo to me:
![image](https://user-images.githubusercontent.com/3532898/52900636-d5f9ab00-31bd-11e9-81b5-e39540b8ea4c.png)

A few with horizontal lines remind me too much of the IBM logo, especially when it is only the lowercase m:
<img src="https://user-images.githubusercontent.com/3532898/52900646-f0cc1f80-31bd-11e9-82ab-87a2242226dd.png" width=125>

**Comment by vsmalladi** [comment]
I really like the idea of the -<M>- logo. I was thinking maybe a typewriter M between the brackets like:
![vintage-typewriter-letter-m-isolated-450w-554049757](https://user-images.githubusercontent.com/1130240/52901763-2b898400-31cd-11e9-93d2-16a55a08c53c.jpg)

**Comment by vincerubinetti** [comment]
@dhimmel @cgreene @agitter @slochower @vsmalladi @ben-heil @zietzm

I've turned the best ideas from above into SVGs, and made a little test bed to easily see and switch between different combinations of brackets, M's, fonts, and colors:

https://jsfiddle.net/5nudzq43/show

![image](https://user-images.githubusercontent.com/8326331/53021712-d39a8980-3427-11e9-9221-581080776cbd.png)

My thought was that people could see what nice combinations they could come up with and post them here. I'd focus on the logo bracket/face combo first, then the font. The colors should probably be an after thought, because the logo should ideally work in the absence of color (to look good when printing monochrome, and just to allow flexibility in the colors in different circumstances/media). Then, perhaps @dhimmel and I can sit down in person and make a short list, which can then be voted on?

Again, keep in mind the "good logo" guidelines in the first post above. Also try to consider which best reflects and indicates what Manubot really is. If I had to boil down Manubot to a few core keyword concepts, these would be mine: manuscript, document, version control, writing, editing, collaboration, automatic ("bot"), open, digital, interactive, print, fair.

**Comment by agitter** [comment]
@vincerubinetti very cool interface.

So far, bracket 3 with face 3 is the most appealing to me.  There are many others I like as well though.  This bracket design hints at input-output when I see it, which speaks to the automation keyword.

I like the way face 1 looks, but I wouldn't recommend using it.  The mustache makes it look very male, and I don't think we want a gendered logo.

**Comment by ypar** [comment]
seconding @agitter. I would recommend against a gendered logo unless it gets adopted to represent more than one colors and genders (e.g. travis-ci).

Always remember [clippy](https://www.theatlantic.com/technology/archive/2015/06/clippy-the-microsoft-office-assistant-is-the-patriarchys-fault/396653/) for any logos or graphical features.

**Comment by cgreene** [comment]
I also like faces 3 and 4. Would the manubot text get changed to match the font face or is it going to stay as is? If it'll stay as is, I also prefer 3.

**Comment by vincerubinetti** [comment]
@cgreene We'll definitely make sure the text font "jives" with whatever the face is, whether it be by making the face M match the text M or by picking our favorite M/face and choosing the best font to match.

**Comment by slochower** [comment]
Another vote for bracket 3, face 3.

**Comment by dhimmel** [comment]
I also like bracket 3, face 3:

> ![image](https://user-images.githubusercontent.com/1117703/53042426-3a359c80-3454-11e9-808c-59aa58ef2260.png)

I'm curious how it'd look to fill the area between brackets with squiggly lines and switching the M to be void space. This would represent written text, and a color scheme could indicate how one document consists of lines from many contributors. However, it's possible this logo would be a bit overwhelming. It also probably only makes sense for the larger dimensions. Something like the favicon would probably have to use the current design?

**Comment by vsmalladi** [comment]
Another vote for bracket 3, face 3

**Comment by vincerubinetti** [comment]
I've whittled the options down to 3 brackets and 3 faces (M's), and 9 fonts. @dhimmel @cgreene @agitter @slochower @vsmalladi @ben-heil @zietzm Please give it one more look and post feedback, if your preference has changed.

https://jsfiddle.net/4at2bhk3/show

**Comment by slochower** [comment]
Thanks @vincerubinetti . I'm bracket 1, face 2 here. I think that's the same as before. Although I think I'd prefer a text with an "M" that matches the logo "M".

**Comment by zietzm** [comment]
I like the vertical letters in face 1 with bracket 1

**Comment by vincerubinetti** [comment]
@slochower I can't really find a good font that matches the exact slanty M we have while keeping the other letters nice and elegant looking. I tried to match the "straight" M to the default font there (4).

Although I don't think it's actually as big of a deal as you might think if the logo M doesn't match the text M exactly. I would only worry if they're both very close but not exact, eg if the middle point of the "straight" M didn't match the font. But if they're different enough (eg slant vs straight) I think it's actually okay.

**Comment by dhimmel** [comment]
I am interested in whether the we could add a down arrow to the right stroke of the M with vertical strokes. This would signify Manubot's use of markdown as its source format. Something like:

> [![](https://camo.githubusercontent.com/45cb95f46d2a4144a5c1aa348db5844e7b9283fd/68747470733a2f2f6d61726b736572762e6769746875622e696f2f6d61726b736572762f6d656469612f6d61726b736572762d726561646d652d62616e6e65722e737667)](https://github.com/markserv/markserv)

**Comment by vincerubinetti** [comment]
![image](https://user-images.githubusercontent.com/8326331/53193230-86144d00-35de-11e9-8a9e-e44a55261cda.png)

I think it might look a little too busy. Also Manubot is very much more than markdown, so I'd be wary of putting it in just to represent one feature. Also it's conceivably that you might switch away from markdown to something else in the very long term future.

**Comment by slochower** [comment]
> Although I don't think it's actually as big of a deal as you might think if the logo M doesn't match the text M exactly. I would only worry if they're both very close but not exact, eg if the middle point of the "straight" M didn't match the font. But if they're different enough (eg slant vs straight) I think it's actually okay.

I guess that's true. I'm not really sure where this logo will be and whether it will be accompanied by text, so I'm happy to defer to your aesthetic judgment.

**Comment by vsmalladi** [comment]
I like bracket 1, face 2 with black text white background

**Comment by agitter** [comment]
Are fonts 8 and 9 the same?  I like both of those paired with bracket 1 face 2.

If we instead use bracket 1 face 1, I instead prefer font 5 (or whatever font matches face 1).

With the brackets, the logo is not square.  Will that be a problem for a favicon?

**Comment by vincerubinetti** [comment]
The people have spoken, and @dhimmel and I have decided on the final logo. You can view the final logo asset files here:

https://github.com/manubot/resources/tree/master/brand

The background and shape colors may change when I design the landing page for `manubot.org`, but everything else should be more or less finalized here.
